/**
 * Server Structure Registry - Auto-generated
 *
 * Contains 17 daemons and 344 commands and 3 adapters.
 * Generated by scripts/generate-structure.ts - DO NOT EDIT MANUALLY
 */

// Server daemons Imports
import { AIProviderDaemonServer } from './../daemons/ai-provider-daemon/server/AIProviderDaemonServer';
import { ArchiveDaemonServer } from './../daemons/archive-daemon/server/ArchiveDaemonServer';
import { ArtifactsDaemonServer } from './../daemons/artifacts-daemon/server/ArtifactsDaemonServer';
import { CommandDaemonServer } from './../daemons/command-daemon/server/CommandDaemonServer';
import { ConsoleDaemonServer } from './../daemons/console-daemon/server/ConsoleDaemonServer';
import { DataDaemonServer } from './../daemons/data-daemon/server/DataDaemonServer';
import { EventsDaemonServer } from './../daemons/events-daemon/server/EventsDaemonServer';
import { GovernanceDaemonServer } from './../daemons/governance-daemon/server/GovernanceDaemonServer';
import { HealthDaemonServer } from './../daemons/health-daemon/server/HealthDaemonServer';
import { LeaseDaemonServer } from './../daemons/lease-daemon/server/LeaseDaemonServer';
import { LoggerDaemonServer } from './../daemons/logger-daemon/server/LoggerDaemonServer';
import { ProxyDaemonServer } from './../daemons/proxy-daemon/server/ProxyDaemonServer';
import { RoomMembershipDaemonServer } from './../daemons/room-membership-daemon/server/RoomMembershipDaemonServer';
import { SessionDaemonServer } from './../daemons/session-daemon/server/SessionDaemonServer';
import { TrainingDaemonServer } from './../daemons/training-daemon/server/TrainingDaemonServer';
import { UserDaemonServer } from './../daemons/user-daemon/server/UserDaemonServer';
import { WidgetDaemonServer } from './../daemons/widget-daemon/server/WidgetDaemonServer';

// Server commands Imports
import { AdapterAdoptServerCommand } from './../commands/adapter/adopt/server/AdapterAdoptServerCommand';
import { AdapterPublishServerCommand } from './../commands/adapter/publish/server/AdapterPublishServerCommand';
import { AdapterSearchServerCommand } from './../commands/adapter/search/server/AdapterSearchServerCommand';
import { AdapterTryServerCommand } from './../commands/adapter/try/server/AdapterTryServerCommand';
import { AgentListServerCommand } from './../commands/agent/list/server/AgentListServerCommand';
import { AgentStartServerCommand } from './../commands/agent/start/server/AgentStartServerCommand';
import { AgentStatusServerCommand } from './../commands/agent/status/server/AgentStatusServerCommand';
import { AgentStopServerCommand } from './../commands/agent/stop/server/AgentStopServerCommand';
import { AdapterTestServerCommand } from './../commands/ai/adapter/test/server/AdapterTestServerCommand';
import { AiAgentServerCommand } from './../commands/ai/agent/server/AiAgentServerCommand';
import { BagOfWordsServerCommand } from './../commands/ai/bag-of-words/server/BagOfWordsServerCommand';
import { AiContextSearchServerCommand } from './../commands/ai/context/search/server/AiContextSearchServerCommand';
import { AiContextSliceServerCommand } from './../commands/ai/context/slice/server/AiContextSliceServerCommand';
import { AICostServerCommand } from './../commands/ai/cost/server/AICostServerCommand';
import { DatasetCreateServerCommand } from './../commands/ai/dataset/create/server/DatasetCreateServerCommand';
import { DatasetListServerCommand } from './../commands/ai/dataset/list/server/DatasetListServerCommand';
import { AiDetectSemanticLoopServerCommand } from './../commands/ai/detect-semantic-loop/server/AiDetectSemanticLoopServerCommand';
import { EmbeddingGenerateServerCommand } from './../commands/ai/embedding/generate/server/EmbeddingGenerateServerCommand';
import { AIGenerateServerCommand } from './../commands/ai/generate/server/AIGenerateServerCommand';
import { GenomeStatsServerCommand } from './../commands/ai/genome/stats/server/GenomeStatsServerCommand';
import { AiKeyDiffServerCommand } from './../commands/ai/key/diff/server/AiKeyDiffServerCommand';
import { AiKeyRemoveServerCommand } from './../commands/ai/key/remove/server/AiKeyRemoveServerCommand';
import { AiKeySaveServerCommand } from './../commands/ai/key/save/server/AiKeySaveServerCommand';
import { AiKeyStatusServerCommand } from './../commands/ai/key/status/server/AiKeyStatusServerCommand';
import { AiKeyTestServerCommand } from './../commands/ai/key/test/server/AiKeyTestServerCommand';
import { AiLocalInferenceStartServerCommand } from './../commands/ai/local-inference/start/server/AiLocalInferenceStartServerCommand';
import { AiLocalInferenceStatusServerCommand } from './../commands/ai/local-inference/status/server/AiLocalInferenceStatusServerCommand';
import { ModelFindServerCommand } from './../commands/ai/model/find/server/ModelFindServerCommand';
import { ModelListServerCommand } from './../commands/ai/model/list/server/ModelListServerCommand';
import { AIProvidersStatusServerCommand } from './../commands/ai/providers/status/server/AIProvidersStatusServerCommand';
import { CodebaseIndexServerCommand } from './../commands/ai/rag/index-codebase/server/CodebaseIndexServerCommand';
import { IndexCreateServerCommand } from './../commands/ai/rag/index/create/server/IndexCreateServerCommand';
import { RAGInspectServerCommand } from './../commands/ai/rag/inspect/server/RAGInspectServerCommand';
import { RagQueryCloseServerCommand } from './../commands/ai/rag/query-close/server/RagQueryCloseServerCommand';
import { RagQueryFetchServerCommand } from './../commands/ai/rag/query-fetch/server/RagQueryFetchServerCommand';
import { RagQueryOpenServerCommand } from './../commands/ai/rag/query-open/server/RagQueryOpenServerCommand';
import { DecisionReportServerCommand } from './../commands/ai/report/decisions/server/DecisionReportServerCommand';
import { AIReportServerCommand } from './../commands/ai/report/server/AIReportServerCommand';
import { ShouldRespondFastServerCommand } from './../commands/ai/should-respond-fast/server/ShouldRespondFastServerCommand';
import { AIShouldRespondServerCommand } from './../commands/ai/should-respond/server/AIShouldRespondServerCommand';
import { AiSleepServerCommand } from './../commands/ai/sleep/server/AiSleepServerCommand';
import { AIStatusServerCommand } from './../commands/ai/status/server/AIStatusServerCommand';
import { ThoughtStreamServerCommand } from './../commands/ai/thoughtstream/server/ThoughtStreamServerCommand';
import { AIValidateResponseServerCommand } from './../commands/ai/validate-response/server/AIValidateResponseServerCommand';
import { AircBridgeServerCommand } from './../commands/airc/bridge/server/AircBridgeServerCommand';
import { AircSendServerCommand } from './../commands/airc/send/server/AircSendServerCommand';
import { AvatarSnapshotServerCommand } from './../commands/avatar/snapshot/server/AvatarSnapshotServerCommand';
import { CanvasStrokeAddServerCommand } from './../commands/canvas/stroke/add/server/CanvasStrokeAddServerCommand';
import { CanvasStrokeListServerCommand } from './../commands/canvas/stroke/list/server/CanvasStrokeListServerCommand';
import { CanvasVisionServerCommand } from './../commands/canvas/vision/server/CanvasVisionServerCommand';
import { ClaudeContextServerCommand } from './../commands/claude/context/server/ClaudeContextServerCommand';
import { ClaudeResumeServerCommand } from './../commands/claude/resume/server/ClaudeResumeServerCommand';
import { ClaudeSnapshotServerCommand } from './../commands/claude/snapshot/server/ClaudeSnapshotServerCommand';
import { CodeDiffServerCommand } from './../commands/code/diff/server/CodeDiffServerCommand';
import { CodeEditServerCommand } from './../commands/code/edit/server/CodeEditServerCommand';
import { CodeGitServerCommand } from './../commands/code/git/server/CodeGitServerCommand';
import { CodeHistoryServerCommand } from './../commands/code/history/server/CodeHistoryServerCommand';
import { CodeReadServerCommand } from './../commands/code/read/server/CodeReadServerCommand';
import { CodeSearchServerCommand } from './../commands/code/search/server/CodeSearchServerCommand';
import { CodeShellExecuteServerCommand } from './../commands/code/shell/execute/server/CodeShellExecuteServerCommand';
import { CodeShellKillServerCommand } from './../commands/code/shell/kill/server/CodeShellKillServerCommand';
import { CodeShellSentinelServerCommand } from './../commands/code/shell/sentinel/server/CodeShellSentinelServerCommand';
import { CodeShellStatusServerCommand } from './../commands/code/shell/status/server/CodeShellStatusServerCommand';
import { CodeShellWatchServerCommand } from './../commands/code/shell/watch/server/CodeShellWatchServerCommand';
import { CodeTreeServerCommand } from './../commands/code/tree/server/CodeTreeServerCommand';
import { CodeUndoServerCommand } from './../commands/code/undo/server/CodeUndoServerCommand';
import { CodeVerifyServerCommand } from './../commands/code/verify/server/CodeVerifyServerCommand';
import { CodeWriteServerCommand } from './../commands/code/write/server/CodeWriteServerCommand';
import { CognitionAdmitInboxMessageServerCommand } from './../commands/cognition/admit-inbox-message/server/CognitionAdmitInboxMessageServerCommand';
import { CognitionRecallEngramsServerCommand } from './../commands/cognition/recall-engrams/server/CognitionRecallEngramsServerCommand';
import { CognitionVisionDescribeServerCommand } from './../commands/cognition/vision-describe/server/CognitionVisionDescribeServerCommand';
import { ActivityCreateServerCommand } from './../commands/collaboration/activity/create/server/ActivityCreateServerCommand';
import { ActivityGetServerCommand } from './../commands/collaboration/activity/get/server/ActivityGetServerCommand';
import { ActivityJoinServerCommand } from './../commands/collaboration/activity/join/server/ActivityJoinServerCommand';
import { ActivityListServerCommand } from './../commands/collaboration/activity/list/server/ActivityListServerCommand';
import { ActivityUpdateServerCommand } from './../commands/collaboration/activity/update/server/ActivityUpdateServerCommand';
import { ChatAnalyzeServerCommand } from './../commands/collaboration/chat/analyze/server/ChatAnalyzeServerCommand';
import { ChatExportServerCommand } from './../commands/collaboration/chat/export/server/ChatExportServerCommand';
import { ChatPollServerCommand } from './../commands/collaboration/chat/poll/server/ChatPollServerCommand';
import { ChatSendServerCommand } from './../commands/collaboration/chat/send/server/ChatSendServerCommand';
import { ContentOpenServerCommand } from './../commands/collaboration/content/open/server/ContentOpenServerCommand';
import { DecisionCreateServerCommand } from './../commands/collaboration/decision/create/server/DecisionCreateServerCommand';
import { DecisionFinalizeServerCommand } from './../commands/collaboration/decision/finalize/server/DecisionFinalizeServerCommand';
import { DecisionListServerCommand } from './../commands/collaboration/decision/list/server/DecisionListServerCommand';
import { DecisionProposeServerCommand } from './../commands/collaboration/decision/propose/server/DecisionProposeServerCommand';
import { DecisionRankServerCommand } from './../commands/collaboration/decision/rank/server/DecisionRankServerCommand';
import { DecisionViewServerCommand } from './../commands/collaboration/decision/view/server/DecisionViewServerCommand';
import { DecisionVoteServerCommand } from './../commands/collaboration/decision/vote/server/DecisionVoteServerCommand';
import { DmServerCommand } from './../commands/collaboration/dm/server/DmServerCommand';
import { LiveExportServerCommand } from './../commands/collaboration/live/export/server/LiveExportServerCommand';
import { LiveJoinServerCommand } from './../commands/collaboration/live/join/server/LiveJoinServerCommand';
import { LiveLeaveServerCommand } from './../commands/collaboration/live/leave/server/LiveLeaveServerCommand';
import { LiveSendServerCommand } from './../commands/collaboration/live/send/server/LiveSendServerCommand';
import { CollaborationLiveStartServerCommand } from './../commands/collaboration/live/start/server/CollaborationLiveStartServerCommand';
import { CollaborationLiveTranscriptionServerCommand } from './../commands/collaboration/live/transcription/server/CollaborationLiveTranscriptionServerCommand';
import { WallListServerCommand } from './../commands/collaboration/wall/list/server/WallListServerCommand';
import { WallReadServerCommand } from './../commands/collaboration/wall/read/server/WallReadServerCommand';
import { WallWriteServerCommand } from './../commands/collaboration/wall/write/server/WallWriteServerCommand';
import { EmotionServerCommand } from './../commands/continuum/emotion/server/EmotionServerCommand';
import { ContinuumSetServerCommand } from './../commands/continuum/set/server/ContinuumSetServerCommand';
import { BackfillVectorsServerCommand } from './../commands/data/backfill-vectors/server/BackfillVectorsServerCommand';
import { DataClearServerCommand } from './../commands/data/clear/server/DataClearServerCommand';
import { DataCloseServerCommand } from './../commands/data/close/server/DataCloseServerCommand';
import { DataCreateServerCommand } from './../commands/data/create/server/DataCreateServerCommand';
import { DataDeleteServerCommand } from './../commands/data/delete/server/DataDeleteServerCommand';
import { GenerateEmbeddingServerCommand } from './../commands/data/generate-embedding/server/GenerateEmbeddingServerCommand';
import { DataListHandlesServerCommand } from './../commands/data/list-handles/server/DataListHandlesServerCommand';
import { DataListServerCommand } from './../commands/data/list/server/DataListServerCommand';
import { DataOpenServerCommand } from './../commands/data/open/server/DataOpenServerCommand';
import { QueryCloseServerCommand } from './../commands/data/query-close/server/QueryCloseServerCommand';
import { QueryNextServerCommand } from './../commands/data/query-next/server/QueryNextServerCommand';
import { QueryOpenServerCommand } from './../commands/data/query-open/server/QueryOpenServerCommand';
import { DataReadServerCommand } from './../commands/data/read/server/DataReadServerCommand';
import { DataSchemaServerCommand } from './../commands/data/schema/server/DataSchemaServerCommand';
import { DataTruncateServerCommand } from './../commands/data/truncate/server/DataTruncateServerCommand';
import { DataUpdateServerCommand } from './../commands/data/update/server/DataUpdateServerCommand';
import { VectorSearchServerCommand } from './../commands/data/vector-search/server/VectorSearchServerCommand';
import { DevActivityServerCommand } from './../commands/dev/activity/server/DevActivityServerCommand';
import { DevBuildFeatureServerCommand } from './../commands/dev/build-feature/server/DevBuildFeatureServerCommand';
import { DevCodeReviewServerCommand } from './../commands/dev/code-review/server/DevCodeReviewServerCommand';
import { DevFixBugServerCommand } from './../commands/dev/fix-bug/server/DevFixBugServerCommand';
import { DevInitServerCommand } from './../commands/dev/init/server/DevInitServerCommand';
import { DevIntegrateServerCommand } from './../commands/dev/integrate/server/DevIntegrateServerCommand';
import { BenchmarkVectorsServerCommand } from './../commands/development/benchmark-vectors/server/BenchmarkVectorsServerCommand';
import { DevelopmentBuildServerCommand } from './../commands/development/build/server/DevelopmentBuildServerCommand';
import { DevelopmentCodeSmellServerCommand } from './../commands/development/code-smell/server/DevelopmentCodeSmellServerCommand';
import { CompileTypescriptServerCommand } from './../commands/development/compile-typescript/server/CompileTypescriptServerCommand';
import { ArtifactsCheckServerCommand } from './../commands/development/debug/artifacts-check/server/ArtifactsCheckServerCommand';
import { ChatSendDebugServerCommand } from './../commands/development/debug/chat-send/server/ChatSendDebugServerCommand';
import { CrudSyncServerCommand } from './../commands/development/debug/crud-sync/server/CrudSyncServerCommand';
import { DebugErrorServerCommand } from './../commands/development/debug/error/server/DebugErrorServerCommand';
import { HtmlInspectorServerCommand } from './../commands/development/debug/html-inspector/server/HtmlInspectorServerCommand';
import { ScrollTestServerCommand } from './../commands/development/debug/scroll-test/server/ScrollTestServerCommand';
import { WidgetCSSServerCommand } from './../commands/development/debug/widget-css/server/WidgetCSSServerCommand';
import { WidgetEventsDebugServerCommand } from './../commands/development/debug/widget-events/server/WidgetEventsDebugServerCommand';
import { WidgetInteractServerCommand } from './../commands/development/debug/widget-interact/server/WidgetInteractServerCommand';
import { WidgetStateServerCommand } from './../commands/development/debug/widget-state/server/WidgetStateServerCommand';
import { ExecServerCommand } from './../commands/development/exec/server/ExecServerCommand';
import { DevelopmentGenerateAuditServerCommand } from './../commands/development/generate/audit/server/DevelopmentGenerateAuditServerCommand';
import { DevelopmentGenerateHelpServerCommand } from './../commands/development/generate/help/server/DevelopmentGenerateHelpServerCommand';
import { DevelopmentGenerateReverseServerCommand } from './../commands/development/generate/reverse/server/DevelopmentGenerateReverseServerCommand';
import { GenerateServerCommand } from './../commands/development/generate/server/GenerateServerCommand';
import { ProposeCommandServerCommand } from './../commands/development/propose-command/server/ProposeCommandServerCommand';
import { SandboxExecuteServerCommand } from './../commands/development/sandbox-execute/server/SandboxExecuteServerCommand';
import { SchemaGenerateServerCommand } from './../commands/development/schema/generate/server/SchemaGenerateServerCommand';
import { ShellExecuteServerCommand } from './../commands/development/shell/execute/server/ShellExecuteServerCommand';
import { TimingServerCommand } from './../commands/development/timing/server/TimingServerCommand';
import { DevelopmentVerifyWebServerCommand } from './../commands/development/verify-web/server/DevelopmentVerifyWebServerCommand';
import { FileAppendServerCommand } from './../commands/file/append/server/FileAppendServerCommand';
import { FileLoadServerCommand } from './../commands/file/load/server/FileLoadServerCommand';
import { FileMimeTypeServerCommand } from './../commands/file/mime-type/server/FileMimeTypeServerCommand';
import { FileSaveServerCommand } from './../commands/file/save/server/FileSaveServerCommand';
import { GenomeAcademyCompetitionServerCommand } from './../commands/genome/academy-competition/server/GenomeAcademyCompetitionServerCommand';
import { GenomeAcademySessionDetailServerCommand } from './../commands/genome/academy-session-detail/server/GenomeAcademySessionDetailServerCommand';
import { GenomeAcademySessionListServerCommand } from './../commands/genome/academy-session-list/server/GenomeAcademySessionListServerCommand';
import { GenomeAcademySessionRestartServerCommand } from './../commands/genome/academy-session-restart/server/GenomeAcademySessionRestartServerCommand';
import { GenomeAcademySessionServerCommand } from './../commands/genome/academy-session/server/GenomeAcademySessionServerCommand';
import { GenomeAdapterBackfillMetricsServerCommand } from './../commands/genome/adapter-backfill-metrics/server/GenomeAdapterBackfillMetricsServerCommand';
import { GenomeAdapterInfoServerCommand } from './../commands/genome/adapter-info/server/GenomeAdapterInfoServerCommand';
import { GenomeAdapterListServerCommand } from './../commands/genome/adapter-list/server/GenomeAdapterListServerCommand';
import { GenomeAdapterPruneServerCommand } from './../commands/genome/adapter-prune/server/GenomeAdapterPruneServerCommand';
import { GenomeAdapterUpdateMetricsServerCommand } from './../commands/genome/adapter-update-metrics/server/GenomeAdapterUpdateMetricsServerCommand';
import { GenomeBatchMicroTuneServerCommand } from './../commands/genome/batch-micro-tune/server/GenomeBatchMicroTuneServerCommand';
import { GenomeBenchmarkServerCommand } from './../commands/genome/benchmark/server/GenomeBenchmarkServerCommand';
import { GenomeComposeServerCommand } from './../commands/genome/compose/server/GenomeComposeServerCommand';
import { GenomeConvertServerCommand } from './../commands/genome/convert/server/GenomeConvertServerCommand';
import { GenomeDatasetImportServerCommand } from './../commands/genome/dataset-import/server/GenomeDatasetImportServerCommand';
import { GenomeDatasetPrepareServerCommand } from './../commands/genome/dataset-prepare/server/GenomeDatasetPrepareServerCommand';
import { GenomeDatasetSynthesizeServerCommand } from './../commands/genome/dataset-synthesize/server/GenomeDatasetSynthesizeServerCommand';
import { GenomeDemoRunServerCommand } from './../commands/genome/demo-run/server/GenomeDemoRunServerCommand';
import { GenomeGapAnalysisServerCommand } from './../commands/genome/gap-analysis/server/GenomeGapAnalysisServerCommand';
import { GenomeJobCreateServerCommand } from './../commands/genome/job-create/server/GenomeJobCreateServerCommand';
import { GenomeJobStatusServerCommand } from './../commands/genome/job-status/server/GenomeJobStatusServerCommand';
import { GenomeLayersServerCommand } from './../commands/genome/layers/server/GenomeLayersServerCommand';
import { GenomeActivateServerCommand } from './../commands/genome/paging-activate/server/GenomeActivateServerCommand';
import { GenomePagingAdapterRegisterServerCommand } from './../commands/genome/paging-adapter-register/server/GenomePagingAdapterRegisterServerCommand';
import { GenomeDeactivateServerCommand } from './../commands/genome/paging-deactivate/server/GenomeDeactivateServerCommand';
import { GenomeRegisterServerCommand } from './../commands/genome/paging-register/server/GenomeRegisterServerCommand';
import { GenomePagingStatsServerCommand } from './../commands/genome/paging-stats/server/GenomePagingStatsServerCommand';
import { GenomeUnregisterServerCommand } from './../commands/genome/paging-unregister/server/GenomeUnregisterServerCommand';
import { GenomePhenotypeValidateServerCommand } from './../commands/genome/phenotype-validate/server/GenomePhenotypeValidateServerCommand';
import { GenomeTrainListJobsServerCommand } from './../commands/genome/train/list-jobs/server/GenomeTrainListJobsServerCommand';
import { GenomeTrainResumeServerCommand } from './../commands/genome/train/resume/server/GenomeTrainResumeServerCommand';
import { GenomeTrainServerCommand } from './../commands/genome/train/server/GenomeTrainServerCommand';
import { GenomeTrainingExportServerCommand } from './../commands/genome/training-export/server/GenomeTrainingExportServerCommand';
import { GenomeTrainingOverviewServerCommand } from './../commands/genome/training-overview/server/GenomeTrainingOverviewServerCommand';
import { GenomeTrainingPipelineServerCommand } from './../commands/genome/training-pipeline/server/GenomeTrainingPipelineServerCommand';
import { GpuStatsServerCommand } from './../commands/gpu/stats/server/GpuStatsServerCommand';
import { GridAuditServerCommand } from './../commands/grid/audit/server/GridAuditServerCommand';
import { GridDeployServerCommand } from './../commands/grid/deploy/server/GridDeployServerCommand';
import { GridDiscoverServerCommand } from './../commands/grid/discover/server/GridDiscoverServerCommand';
import { GridJobControlServerCommand } from './../commands/grid/job-control/server/GridJobControlServerCommand';
import { GridJobQueueServerCommand } from './../commands/grid/job-queue/server/GridJobQueueServerCommand';
import { GridJobSubmitServerCommand } from './../commands/grid/job-submit/server/GridJobSubmitServerCommand';
import { GridNodeStatusServerCommand } from './../commands/grid/node-status/server/GridNodeStatusServerCommand';
import { GridNodesServerCommand } from './../commands/grid/nodes/server/GridNodesServerCommand';
import { GridPairServerCommand } from './../commands/grid/pair/server/GridPairServerCommand';
import { GridPingServerCommand } from './../commands/grid/ping/server/GridPingServerCommand';
import { GridRouteServerCommand } from './../commands/grid/route/server/GridRouteServerCommand';
import { GridSendServerCommand } from './../commands/grid/send/server/GridSendServerCommand';
import { GridSetupCheckServerCommand } from './../commands/grid/setup-check/server/GridSetupCheckServerCommand';
import { GridStatusServerCommand } from './../commands/grid/status/server/GridStatusServerCommand';
import { GridTrustServerCommand } from './../commands/grid/trust/server/GridTrustServerCommand';
import { HelpServerCommand } from './../commands/help/server/HelpServerCommand';
import { IndicatorServerCommand } from './../commands/indicator/server/IndicatorServerCommand';
import { InferenceCapacityServerCommand } from './../commands/inference/capacity/server/InferenceCapacityServerCommand';
import { InferenceGenerateServerCommand } from './../commands/inference/generate/server/InferenceGenerateServerCommand';
import { InterfaceBrowserCapabilitiesServerCommand } from './../commands/interface/browser/capabilities/server/InterfaceBrowserCapabilitiesServerCommand';
import { ClickServerCommand } from './../commands/interface/click/server/ClickServerCommand';
import { GetTextServerCommand } from './../commands/interface/get-text/server/GetTextServerCommand';
import { InterfaceInteractServerCommand } from './../commands/interface/interact/server/InterfaceInteractServerCommand';
import { InterfaceLaunchUrlServerCommand } from './../commands/interface/launch/url/server/InterfaceLaunchUrlServerCommand';
import { NavigateServerCommand } from './../commands/interface/navigate/server/NavigateServerCommand';
import { InterfacePageFillServerCommand } from './../commands/interface/page/fill/server/InterfacePageFillServerCommand';
import { InterfacePageFormsServerCommand } from './../commands/interface/page/forms/server/InterfacePageFormsServerCommand';
import { InterfacePageSubmitServerCommand } from './../commands/interface/page/submit/server/InterfacePageSubmitServerCommand';
import { ProxyNavigateServerCommand } from './../commands/interface/proxy-navigate/server/ProxyNavigateServerCommand';
import { ScreenshotServerCommand } from './../commands/interface/screenshot/server/ScreenshotServerCommand';
import { ScrollServerCommand } from './../commands/interface/scroll/server/ScrollServerCommand';
import { TypeServerCommand } from './../commands/interface/type/server/TypeServerCommand';
import { WaitForElementServerCommand } from './../commands/interface/wait-for-element/server/WaitForElementServerCommand';
import { WebFetchServerCommand } from './../commands/interface/web/fetch/server/WebFetchServerCommand';
import { WebSearchServerCommand } from './../commands/interface/web/search/server/WebSearchServerCommand';
import { InterfaceWebmcpCallServerCommand } from './../commands/interface/webmcp/call/server/InterfaceWebmcpCallServerCommand';
import { InterfaceWebmcpDiscoverServerCommand } from './../commands/interface/webmcp/discover/server/InterfaceWebmcpDiscoverServerCommand';
import { ListServerCommand } from './../commands/list/server/ListServerCommand';
import { LoggingDisableServerCommand } from './../commands/logging/disable/server/LoggingDisableServerCommand';
import { LoggingEnableServerCommand } from './../commands/logging/enable/server/LoggingEnableServerCommand';
import { LoggingStatusServerCommand } from './../commands/logging/status/server/LoggingStatusServerCommand';
import { LogsConfigServerCommand } from './../commands/logs/config/server/LogsConfigServerCommand';
import { LogsListServerCommand } from './../commands/logs/list/server/LogsListServerCommand';
import { LogsReadServerCommand } from './../commands/logs/read/server/LogsReadServerCommand';
import { LogsSearchServerCommand } from './../commands/logs/search/server/LogsSearchServerCommand';
import { LogsStatsServerCommand } from './../commands/logs/stats/server/LogsStatsServerCommand';
import { MediaPrewarmServerCommand } from './../commands/media/prewarm/server/MediaPrewarmServerCommand';
import { MediaProcessServerCommand } from './../commands/media/process/server/MediaProcessServerCommand';
import { MediaResizeServerCommand } from './../commands/media/resize/server/MediaResizeServerCommand';
import { MigrationCutoverServerCommand } from './../commands/migration/cutover/server/MigrationCutoverServerCommand';
import { MigrationPauseServerCommand } from './../commands/migration/pause/server/MigrationPauseServerCommand';
import { MigrationResumeServerCommand } from './../commands/migration/resume/server/MigrationResumeServerCommand';
import { MigrationRollbackServerCommand } from './../commands/migration/rollback/server/MigrationRollbackServerCommand';
import { MigrationStartServerCommand } from './../commands/migration/start/server/MigrationStartServerCommand';
import { MigrationStatusServerCommand } from './../commands/migration/status/server/MigrationStatusServerCommand';
import { MigrationVerifyServerCommand } from './../commands/migration/verify/server/MigrationVerifyServerCommand';
import { ModelDownloadServerCommand } from './../commands/model/download/server/ModelDownloadServerCommand';
import { ModelForgeStatusServerCommand } from './../commands/model/forge-status/server/ModelForgeStatusServerCommand';
import { ModelForgeServerCommand } from './../commands/model/forge/server/ModelForgeServerCommand';
import { ModelIntrospectServerCommand } from './../commands/model/introspect/server/ModelIntrospectServerCommand';
import { ModelListPublishedServerCommand } from './../commands/model/list-published/server/ModelListPublishedServerCommand';
import { ModelPublishServerCommand } from './../commands/model/publish/server/ModelPublishServerCommand';
import { ModelSearchServerCommand } from './../commands/model/search/server/ModelSearchServerCommand';
import { OntologyBridgeTranslateServerCommand } from './../commands/ontology/bridge/translate/server/OntologyBridgeTranslateServerCommand';
import { OntologyConceptLookupBatchServerCommand } from './../commands/ontology/concept/lookup-batch/server/OntologyConceptLookupBatchServerCommand';
import { PersonaAllocateServerCommand } from './../commands/persona/allocate/server/PersonaAllocateServerCommand';
import { PersonaGenomeServerCommand } from './../commands/persona/genome/server/PersonaGenomeServerCommand';
import { GenomeCaptureFeedbackServerCommand } from './../commands/persona/learning/capture-feedback/server/GenomeCaptureFeedbackServerCommand';
import { GenomeCaptureInteractionServerCommand } from './../commands/persona/learning/capture-interaction/server/GenomeCaptureInteractionServerCommand';
import { GenomeMultiAgentLearnServerCommand } from './../commands/persona/learning/multi-agent-learn/server/GenomeMultiAgentLearnServerCommand';
import { PersonaLearningPatternCaptureServerCommand } from './../commands/persona/learning/pattern/capture/server/PersonaLearningPatternCaptureServerCommand';
import { PersonaLearningPatternEndorseServerCommand } from './../commands/persona/learning/pattern/endorse/server/PersonaLearningPatternEndorseServerCommand';
import { PersonaLearningPatternQueryServerCommand } from './../commands/persona/learning/pattern/query/server/PersonaLearningPatternQueryServerCommand';
import { PingServerCommand } from './../commands/ping/server/PingServerCommand';
import { PlasticityAnalyzeServerCommand } from './../commands/plasticity/analyze/server/PlasticityAnalyzeServerCommand';
import { PlasticityCompactServerCommand } from './../commands/plasticity/compact/server/PlasticityCompactServerCommand';
import { PlasticityCompressServerCommand } from './../commands/plasticity/compress/server/PlasticityCompressServerCommand';
import { PlasticityPipelineServerCommand } from './../commands/plasticity/pipeline/server/PlasticityPipelineServerCommand';
import { PlasticityTopologyServerCommand } from './../commands/plasticity/topology/server/PlasticityTopologyServerCommand';
import { PositronCursorServerCommand } from './../commands/positron/cursor/server/PositronCursorServerCommand';
import { ProcessRegistryServerCommand } from './../commands/process-registry/server/ProcessRegistryServerCommand';
import { RAGBudgetServerCommand } from './../commands/rag/budget/server/RAGBudgetServerCommand';
import { RAGLoadServerCommand } from './../commands/rag/load/server/RAGLoadServerCommand';
import { RecipeGenerateServerCommand } from './../commands/recipe/generate/server/RecipeGenerateServerCommand';
import { RecipeListServerCommand } from './../commands/recipe/list/server/RecipeListServerCommand';
import { RecipeRunServerCommand } from './../commands/recipe/run/server/RecipeRunServerCommand';
import { RuntimeMetricsServerCommand } from './../commands/runtime/metrics/server/RuntimeMetricsServerCommand';
import { SearchExecuteServerCommand } from './../commands/search/execute/server/SearchExecuteServerCommand';
import { SearchListServerCommand } from './../commands/search/list/server/SearchListServerCommand';
import { SearchParamsServerCommand } from './../commands/search/params/server/SearchParamsServerCommand';
import { SearchVectorServerCommand } from './../commands/search/vector/server/SearchVectorServerCommand';
import { SecuritySetupServerCommand } from './../commands/security/setup/server/SecuritySetupServerCommand';
import { SentinelApproveServerCommand } from './../commands/sentinel/approve/server/SentinelApproveServerCommand';
import { SentinelCancelServerCommand } from './../commands/sentinel/cancel/server/SentinelCancelServerCommand';
import { SentinelCleanupServerCommand } from './../commands/sentinel/cleanup/server/SentinelCleanupServerCommand';
import { SentinelCodingAgentServerCommand } from './../commands/sentinel/coding-agent/server/SentinelCodingAgentServerCommand';
import { SentinelEscalateServerCommand } from './../commands/sentinel/escalate/server/SentinelEscalateServerCommand';
import { SentinelExtendBudgetServerCommand } from './../commands/sentinel/extend-budget/server/SentinelExtendBudgetServerCommand';
import { SentinelListServerCommand } from './../commands/sentinel/list/server/SentinelListServerCommand';
import { SentinelLoadServerCommand } from './../commands/sentinel/load/server/SentinelLoadServerCommand';
import { SentinelLogsListServerCommand } from './../commands/sentinel/logs/list/server/SentinelLogsListServerCommand';
import { SentinelLogsReadServerCommand } from './../commands/sentinel/logs/read/server/SentinelLogsReadServerCommand';
import { SentinelLogsTailServerCommand } from './../commands/sentinel/logs/tail/server/SentinelLogsTailServerCommand';
import { SentinelResumeServerCommand } from './../commands/sentinel/resume/server/SentinelResumeServerCommand';
import { SentinelRunServerCommand } from './../commands/sentinel/run/server/SentinelRunServerCommand';
import { SentinelSaveServerCommand } from './../commands/sentinel/save/server/SentinelSaveServerCommand';
import { SentinelStatusServerCommand } from './../commands/sentinel/status/server/SentinelStatusServerCommand';
import { SentinelWebResearchServerCommand } from './../commands/sentinel/web-research/server/SentinelWebResearchServerCommand';
import { SessionCreateServerCommand } from './../commands/session/create/server/SessionCreateServerCommand';
import { SessionDestroyServerCommand } from './../commands/session/destroy/server/SessionDestroyServerCommand';
import { SessionGetIdServerCommand } from './../commands/session/get-id/server/SessionGetIdServerCommand';
import { SessionGetUserServerCommand } from './../commands/session/get-user/server/SessionGetUserServerCommand';
import { SkillActivateServerCommand } from './../commands/skill/activate/server/SkillActivateServerCommand';
import { SkillGenerateServerCommand } from './../commands/skill/generate/server/SkillGenerateServerCommand';
import { SkillListServerCommand } from './../commands/skill/list/server/SkillListServerCommand';
import { SkillProposeServerCommand } from './../commands/skill/propose/server/SkillProposeServerCommand';
import { SkillValidateServerCommand } from './../commands/skill/validate/server/SkillValidateServerCommand';
import { StateContentCloseServerCommand } from './../commands/state/content/close/server/StateContentCloseServerCommand';
import { StateContentSwitchServerCommand } from './../commands/state/content/switch/server/StateContentSwitchServerCommand';
import { StateCreateServerCommand } from './../commands/state/create/server/StateCreateServerCommand';
import { StateGetServerCommand } from './../commands/state/get/server/StateGetServerCommand';
import { StateUpdateServerCommand } from './../commands/state/update/server/StateUpdateServerCommand';
import { DaemonsServerCommand } from './../commands/system/daemons/server/DaemonsServerCommand';
import { SystemDockerTierStatsServerCommand } from './../commands/system/docker-tier-stats/server/SystemDockerTierStatsServerCommand';
import { SystemMetricsServerCommand } from './../commands/system/metrics/server/SystemMetricsServerCommand';
import { SystemResourcesServerCommand } from './../commands/system/resources/server/SystemResourcesServerCommand';
import { ThemeGetServerCommand } from './../commands/theme/get/server/ThemeGetServerCommand';
import { ThemeListServerCommand } from './../commands/theme/list/server/ThemeListServerCommand';
import { ThemeSetServerCommand } from './../commands/theme/set/server/ThemeSetServerCommand';
import { TrainingImportServerCommand } from './../commands/training/import/server/TrainingImportServerCommand';
import { UserCreateServerCommand } from './../commands/user/create/server/UserCreateServerCommand';
import { UserGetMeServerCommand } from './../commands/user/get-me/server/UserGetMeServerCommand';
import { UserListServerCommand } from './../commands/user/list/server/UserListServerCommand';
import { DocsListServerCommand } from './../commands/utilities/docs/list/server/DocsListServerCommand';
import { DocsReadServerCommand } from './../commands/utilities/docs/read/server/DocsReadServerCommand';
import { DocsSearchServerCommand } from './../commands/utilities/docs/search/server/DocsSearchServerCommand';
import { HelloServerCommand } from './../commands/utilities/hello/server/HelloServerCommand';
import { PipeChainServerCommand } from './../commands/utilities/pipe/chain/server/PipeChainServerCommand';
import { VoiceSnapshotParticipantServerCommand } from './../commands/voice/snapshot-participant/server/VoiceSnapshotParticipantServerCommand';
import { VoiceSnapshotRoomServerCommand } from './../commands/voice/snapshot-room/server/VoiceSnapshotRoomServerCommand';
import { VoiceStartServerCommand } from './../commands/voice/start/server/VoiceStartServerCommand';
import { VoiceStopServerCommand } from './../commands/voice/stop/server/VoiceStopServerCommand';
import { VoiceSynthesizeServerCommand } from './../commands/voice/synthesize/server/VoiceSynthesizeServerCommand';
import { VoiceTranscribeServerCommand } from './../commands/voice/transcribe/server/VoiceTranscribeServerCommand';
import { GitCommitServerCommand } from './../commands/workspace/git/commit/server/GitCommitServerCommand';
import { GitPushServerCommand } from './../commands/workspace/git/push/server/GitPushServerCommand';
import { GitStatusServerCommand } from './../commands/workspace/git/status/server/GitStatusServerCommand';
import { GitWorkspaceCleanServerCommand } from './../commands/workspace/git/workspace/clean/server/GitWorkspaceCleanServerCommand';
import { GitWorkspaceInitServerCommand } from './../commands/workspace/git/workspace/init/server/GitWorkspaceInitServerCommand';
import { ImageGenerateRealisticServerCommand } from './../commands/image/generate-realistic/server/ImageGenerateRealisticServerCommand';
import { WorkspaceListServerCommand } from './../commands/workspace/list/server/WorkspaceListServerCommand';
import { RecipeLoadServerCommand } from './../commands/workspace/recipe/load/server/RecipeLoadServerCommand';
import { TaskCompleteServerCommand } from './../commands/workspace/task/complete/server/TaskCompleteServerCommand';
import { TaskCreateServerCommand } from './../commands/workspace/task/create/server/TaskCreateServerCommand';
import { TaskListServerCommand } from './../commands/workspace/task/list/server/TaskListServerCommand';
import { TreeServerCommand } from './../commands/workspace/tree/server/TreeServerCommand';

// Server adapters Imports
import { UDPMulticastTransportServer } from './../system/transports/udp-multicast-transport/server/UDPMulticastTransportServer';
import { WebSocketTransportClientServer } from './../system/transports/websocket-transport/server/WebSocketTransportClientServer';
import { WebSocketTransportServer } from './../system/transports/websocket-transport/server/WebSocketTransportServer';

// Types
import type { DaemonEntry } from './../daemons/command-daemon/shared/DaemonBase';
import type { CommandEntry } from './../daemons/command-daemon/shared/CommandBase';
import type { AdapterEntry } from './../system/transports/shared/TransportBase';

/**
 * Server Environment Registry
 */
export const SERVER_DAEMONS: DaemonEntry[] = [
{
    name: 'AIProviderDaemon',
    className: 'AIProviderDaemonServer',
    daemonClass: AIProviderDaemonServer
  },
{
    name: 'ArchiveDaemon',
    className: 'ArchiveDaemonServer',
    daemonClass: ArchiveDaemonServer
  },
{
    name: 'ArtifactsDaemon',
    className: 'ArtifactsDaemonServer',
    daemonClass: ArtifactsDaemonServer
  },
{
    name: 'CommandDaemon',
    className: 'CommandDaemonServer',
    daemonClass: CommandDaemonServer
  },
{
    name: 'ConsoleDaemon',
    className: 'ConsoleDaemonServer',
    daemonClass: ConsoleDaemonServer
  },
{
    name: 'DataDaemon',
    className: 'DataDaemonServer',
    daemonClass: DataDaemonServer
  },
{
    name: 'EventsDaemon',
    className: 'EventsDaemonServer',
    daemonClass: EventsDaemonServer
  },
{
    name: 'GovernanceDaemon',
    className: 'GovernanceDaemonServer',
    daemonClass: GovernanceDaemonServer
  },
{
    name: 'HealthDaemon',
    className: 'HealthDaemonServer',
    daemonClass: HealthDaemonServer
  },
{
    name: 'LeaseDaemon',
    className: 'LeaseDaemonServer',
    daemonClass: LeaseDaemonServer
  },
{
    name: 'LoggerDaemon',
    className: 'LoggerDaemonServer',
    daemonClass: LoggerDaemonServer
  },
{
    name: 'ProxyDaemon',
    className: 'ProxyDaemonServer',
    daemonClass: ProxyDaemonServer
  },
{
    name: 'RoomMembershipDaemon',
    className: 'RoomMembershipDaemonServer',
    daemonClass: RoomMembershipDaemonServer
  },
{
    name: 'SessionDaemon',
    className: 'SessionDaemonServer',
    daemonClass: SessionDaemonServer
  },
{
    name: 'TrainingDaemon',
    className: 'TrainingDaemonServer',
    daemonClass: TrainingDaemonServer
  },
{
    name: 'UserDaemon',
    className: 'UserDaemonServer',
    daemonClass: UserDaemonServer
  },
{
    name: 'WidgetDaemon',
    className: 'WidgetDaemonServer',
    daemonClass: WidgetDaemonServer
  }
];

export const SERVER_COMMANDS: CommandEntry[] = [
{
    name: 'adapter/adopt',
    className: 'AdapterAdoptServerCommand',
    commandClass: AdapterAdoptServerCommand
  },
{
    name: 'adapter/publish',
    className: 'AdapterPublishServerCommand',
    commandClass: AdapterPublishServerCommand
  },
{
    name: 'adapter/search',
    className: 'AdapterSearchServerCommand',
    commandClass: AdapterSearchServerCommand
  },
{
    name: 'adapter/try',
    className: 'AdapterTryServerCommand',
    commandClass: AdapterTryServerCommand
  },
{
    name: 'agent/list',
    className: 'AgentListServerCommand',
    commandClass: AgentListServerCommand
  },
{
    name: 'agent/start',
    className: 'AgentStartServerCommand',
    commandClass: AgentStartServerCommand
  },
{
    name: 'agent/status',
    className: 'AgentStatusServerCommand',
    commandClass: AgentStatusServerCommand
  },
{
    name: 'agent/stop',
    className: 'AgentStopServerCommand',
    commandClass: AgentStopServerCommand
  },
{
    name: 'ai/adapter/test',
    className: 'AdapterTestServerCommand',
    commandClass: AdapterTestServerCommand
  },
{
    name: 'ai/agent',
    className: 'AiAgentServerCommand',
    commandClass: AiAgentServerCommand
  },
{
    name: 'ai/bag-of-words',
    className: 'BagOfWordsServerCommand',
    commandClass: BagOfWordsServerCommand
  },
{
    name: 'ai/context/search',
    className: 'AiContextSearchServerCommand',
    commandClass: AiContextSearchServerCommand
  },
{
    name: 'ai/context/slice',
    className: 'AiContextSliceServerCommand',
    commandClass: AiContextSliceServerCommand
  },
{
    name: 'ai/cost',
    className: 'AICostServerCommand',
    commandClass: AICostServerCommand
  },
{
    name: 'ai/dataset/create',
    className: 'DatasetCreateServerCommand',
    commandClass: DatasetCreateServerCommand
  },
{
    name: 'ai/dataset/list',
    className: 'DatasetListServerCommand',
    commandClass: DatasetListServerCommand
  },
{
    name: 'ai/detect-semantic-loop',
    className: 'AiDetectSemanticLoopServerCommand',
    commandClass: AiDetectSemanticLoopServerCommand
  },
{
    name: 'ai/embedding/generate',
    className: 'EmbeddingGenerateServerCommand',
    commandClass: EmbeddingGenerateServerCommand
  },
{
    name: 'ai/generate',
    className: 'AIGenerateServerCommand',
    commandClass: AIGenerateServerCommand
  },
{
    name: 'ai/genome/stats',
    className: 'GenomeStatsServerCommand',
    commandClass: GenomeStatsServerCommand
  },
{
    name: 'ai/key/diff',
    className: 'AiKeyDiffServerCommand',
    commandClass: AiKeyDiffServerCommand
  },
{
    name: 'ai/key/remove',
    className: 'AiKeyRemoveServerCommand',
    commandClass: AiKeyRemoveServerCommand
  },
{
    name: 'ai/key/save',
    className: 'AiKeySaveServerCommand',
    commandClass: AiKeySaveServerCommand
  },
{
    name: 'ai/key/status',
    className: 'AiKeyStatusServerCommand',
    commandClass: AiKeyStatusServerCommand
  },
{
    name: 'ai/key/test',
    className: 'AiKeyTestServerCommand',
    commandClass: AiKeyTestServerCommand
  },
{
    name: 'ai/local-inference/start',
    className: 'AiLocalInferenceStartServerCommand',
    commandClass: AiLocalInferenceStartServerCommand
  },
{
    name: 'ai/local-inference/status',
    className: 'AiLocalInferenceStatusServerCommand',
    commandClass: AiLocalInferenceStatusServerCommand
  },
{
    name: 'ai/model/find',
    className: 'ModelFindServerCommand',
    commandClass: ModelFindServerCommand
  },
{
    name: 'ai/model/list',
    className: 'ModelListServerCommand',
    commandClass: ModelListServerCommand
  },
{
    name: 'ai/providers/status',
    className: 'AIProvidersStatusServerCommand',
    commandClass: AIProvidersStatusServerCommand
  },
{
    name: 'ai/rag/index-codebase',
    className: 'CodebaseIndexServerCommand',
    commandClass: CodebaseIndexServerCommand
  },
{
    name: 'ai/rag/index/create',
    className: 'IndexCreateServerCommand',
    commandClass: IndexCreateServerCommand
  },
{
    name: 'ai/rag/inspect',
    className: 'RAGInspectServerCommand',
    commandClass: RAGInspectServerCommand
  },
{
    name: 'ai/rag/query-close',
    className: 'RagQueryCloseServerCommand',
    commandClass: RagQueryCloseServerCommand
  },
{
    name: 'ai/rag/query-fetch',
    className: 'RagQueryFetchServerCommand',
    commandClass: RagQueryFetchServerCommand
  },
{
    name: 'ai/rag/query-open',
    className: 'RagQueryOpenServerCommand',
    commandClass: RagQueryOpenServerCommand
  },
{
    name: 'ai/report/decisions',
    className: 'DecisionReportServerCommand',
    commandClass: DecisionReportServerCommand
  },
{
    name: 'ai/report',
    className: 'AIReportServerCommand',
    commandClass: AIReportServerCommand
  },
{
    name: 'ai/should-respond-fast',
    className: 'ShouldRespondFastServerCommand',
    commandClass: ShouldRespondFastServerCommand
  },
{
    name: 'ai/should-respond',
    className: 'AIShouldRespondServerCommand',
    commandClass: AIShouldRespondServerCommand
  },
{
    name: 'ai/sleep',
    className: 'AiSleepServerCommand',
    commandClass: AiSleepServerCommand
  },
{
    name: 'ai/status',
    className: 'AIStatusServerCommand',
    commandClass: AIStatusServerCommand
  },
{
    name: 'ai/thoughtstream',
    className: 'ThoughtStreamServerCommand',
    commandClass: ThoughtStreamServerCommand
  },
{
    name: 'ai/validate-response',
    className: 'AIValidateResponseServerCommand',
    commandClass: AIValidateResponseServerCommand
  },
{
    name: 'airc/bridge',
    className: 'AircBridgeServerCommand',
    commandClass: AircBridgeServerCommand
  },
{
    name: 'airc/send',
    className: 'AircSendServerCommand',
    commandClass: AircSendServerCommand
  },
{
    name: 'avatar/snapshot',
    className: 'AvatarSnapshotServerCommand',
    commandClass: AvatarSnapshotServerCommand
  },
{
    name: 'canvas/stroke/add',
    className: 'CanvasStrokeAddServerCommand',
    commandClass: CanvasStrokeAddServerCommand
  },
{
    name: 'canvas/stroke/list',
    className: 'CanvasStrokeListServerCommand',
    commandClass: CanvasStrokeListServerCommand
  },
{
    name: 'canvas/vision',
    className: 'CanvasVisionServerCommand',
    commandClass: CanvasVisionServerCommand
  },
{
    name: 'claude/context',
    className: 'ClaudeContextServerCommand',
    commandClass: ClaudeContextServerCommand
  },
{
    name: 'claude/resume',
    className: 'ClaudeResumeServerCommand',
    commandClass: ClaudeResumeServerCommand
  },
{
    name: 'claude/snapshot',
    className: 'ClaudeSnapshotServerCommand',
    commandClass: ClaudeSnapshotServerCommand
  },
{
    name: 'code/diff',
    className: 'CodeDiffServerCommand',
    commandClass: CodeDiffServerCommand
  },
{
    name: 'code/edit',
    className: 'CodeEditServerCommand',
    commandClass: CodeEditServerCommand
  },
{
    name: 'code/git',
    className: 'CodeGitServerCommand',
    commandClass: CodeGitServerCommand
  },
{
    name: 'code/history',
    className: 'CodeHistoryServerCommand',
    commandClass: CodeHistoryServerCommand
  },
{
    name: 'code/read',
    className: 'CodeReadServerCommand',
    commandClass: CodeReadServerCommand
  },
{
    name: 'code/search',
    className: 'CodeSearchServerCommand',
    commandClass: CodeSearchServerCommand
  },
{
    name: 'code/shell/execute',
    className: 'CodeShellExecuteServerCommand',
    commandClass: CodeShellExecuteServerCommand
  },
{
    name: 'code/shell/kill',
    className: 'CodeShellKillServerCommand',
    commandClass: CodeShellKillServerCommand
  },
{
    name: 'code/shell/sentinel',
    className: 'CodeShellSentinelServerCommand',
    commandClass: CodeShellSentinelServerCommand
  },
{
    name: 'code/shell/status',
    className: 'CodeShellStatusServerCommand',
    commandClass: CodeShellStatusServerCommand
  },
{
    name: 'code/shell/watch',
    className: 'CodeShellWatchServerCommand',
    commandClass: CodeShellWatchServerCommand
  },
{
    name: 'code/tree',
    className: 'CodeTreeServerCommand',
    commandClass: CodeTreeServerCommand
  },
{
    name: 'code/undo',
    className: 'CodeUndoServerCommand',
    commandClass: CodeUndoServerCommand
  },
{
    name: 'code/verify',
    className: 'CodeVerifyServerCommand',
    commandClass: CodeVerifyServerCommand
  },
{
    name: 'code/write',
    className: 'CodeWriteServerCommand',
    commandClass: CodeWriteServerCommand
  },
{
    name: 'cognition/admit-inbox-message',
    className: 'CognitionAdmitInboxMessageServerCommand',
    commandClass: CognitionAdmitInboxMessageServerCommand
  },
{
    name: 'cognition/recall-engrams',
    className: 'CognitionRecallEngramsServerCommand',
    commandClass: CognitionRecallEngramsServerCommand
  },
{
    name: 'cognition/vision-describe',
    className: 'CognitionVisionDescribeServerCommand',
    commandClass: CognitionVisionDescribeServerCommand
  },
{
    name: 'collaboration/activity/create',
    className: 'ActivityCreateServerCommand',
    commandClass: ActivityCreateServerCommand
  },
{
    name: 'collaboration/activity/get',
    className: 'ActivityGetServerCommand',
    commandClass: ActivityGetServerCommand
  },
{
    name: 'collaboration/activity/join',
    className: 'ActivityJoinServerCommand',
    commandClass: ActivityJoinServerCommand
  },
{
    name: 'collaboration/activity/list',
    className: 'ActivityListServerCommand',
    commandClass: ActivityListServerCommand
  },
{
    name: 'collaboration/activity/update',
    className: 'ActivityUpdateServerCommand',
    commandClass: ActivityUpdateServerCommand
  },
{
    name: 'collaboration/chat/analyze',
    className: 'ChatAnalyzeServerCommand',
    commandClass: ChatAnalyzeServerCommand
  },
{
    name: 'collaboration/chat/export',
    className: 'ChatExportServerCommand',
    commandClass: ChatExportServerCommand
  },
{
    name: 'collaboration/chat/poll',
    className: 'ChatPollServerCommand',
    commandClass: ChatPollServerCommand
  },
{
    name: 'collaboration/chat/send',
    className: 'ChatSendServerCommand',
    commandClass: ChatSendServerCommand
  },
{
    name: 'collaboration/content/open',
    className: 'ContentOpenServerCommand',
    commandClass: ContentOpenServerCommand
  },
{
    name: 'collaboration/decision/create',
    className: 'DecisionCreateServerCommand',
    commandClass: DecisionCreateServerCommand
  },
{
    name: 'collaboration/decision/finalize',
    className: 'DecisionFinalizeServerCommand',
    commandClass: DecisionFinalizeServerCommand
  },
{
    name: 'collaboration/decision/list',
    className: 'DecisionListServerCommand',
    commandClass: DecisionListServerCommand
  },
{
    name: 'collaboration/decision/propose',
    className: 'DecisionProposeServerCommand',
    commandClass: DecisionProposeServerCommand
  },
{
    name: 'collaboration/decision/rank',
    className: 'DecisionRankServerCommand',
    commandClass: DecisionRankServerCommand
  },
{
    name: 'collaboration/decision/view',
    className: 'DecisionViewServerCommand',
    commandClass: DecisionViewServerCommand
  },
{
    name: 'collaboration/decision/vote',
    className: 'DecisionVoteServerCommand',
    commandClass: DecisionVoteServerCommand
  },
{
    name: 'collaboration/dm',
    className: 'DmServerCommand',
    commandClass: DmServerCommand
  },
{
    name: 'collaboration/live/export',
    className: 'LiveExportServerCommand',
    commandClass: LiveExportServerCommand
  },
{
    name: 'collaboration/live/join',
    className: 'LiveJoinServerCommand',
    commandClass: LiveJoinServerCommand
  },
{
    name: 'collaboration/live/leave',
    className: 'LiveLeaveServerCommand',
    commandClass: LiveLeaveServerCommand
  },
{
    name: 'collaboration/live/send',
    className: 'LiveSendServerCommand',
    commandClass: LiveSendServerCommand
  },
{
    name: 'collaboration/live/start',
    className: 'CollaborationLiveStartServerCommand',
    commandClass: CollaborationLiveStartServerCommand
  },
{
    name: 'collaboration/live/transcription',
    className: 'CollaborationLiveTranscriptionServerCommand',
    commandClass: CollaborationLiveTranscriptionServerCommand
  },
{
    name: 'collaboration/wall/list',
    className: 'WallListServerCommand',
    commandClass: WallListServerCommand
  },
{
    name: 'collaboration/wall/read',
    className: 'WallReadServerCommand',
    commandClass: WallReadServerCommand
  },
{
    name: 'collaboration/wall/write',
    className: 'WallWriteServerCommand',
    commandClass: WallWriteServerCommand
  },
{
    name: 'continuum/emotion',
    className: 'EmotionServerCommand',
    commandClass: EmotionServerCommand
  },
{
    name: 'continuum/set',
    className: 'ContinuumSetServerCommand',
    commandClass: ContinuumSetServerCommand
  },
{
    name: 'data/backfill-vectors',
    className: 'BackfillVectorsServerCommand',
    commandClass: BackfillVectorsServerCommand
  },
{
    name: 'data/clear',
    className: 'DataClearServerCommand',
    commandClass: DataClearServerCommand
  },
{
    name: 'data/close',
    className: 'DataCloseServerCommand',
    commandClass: DataCloseServerCommand
  },
{
    name: 'data/create',
    className: 'DataCreateServerCommand',
    commandClass: DataCreateServerCommand
  },
{
    name: 'data/delete',
    className: 'DataDeleteServerCommand',
    commandClass: DataDeleteServerCommand
  },
{
    name: 'data/generate-embedding',
    className: 'GenerateEmbeddingServerCommand',
    commandClass: GenerateEmbeddingServerCommand
  },
{
    name: 'data/list-handles',
    className: 'DataListHandlesServerCommand',
    commandClass: DataListHandlesServerCommand
  },
{
    name: 'data/list',
    className: 'DataListServerCommand',
    commandClass: DataListServerCommand
  },
{
    name: 'data/open',
    className: 'DataOpenServerCommand',
    commandClass: DataOpenServerCommand
  },
{
    name: 'data/query-close',
    className: 'QueryCloseServerCommand',
    commandClass: QueryCloseServerCommand
  },
{
    name: 'data/query-next',
    className: 'QueryNextServerCommand',
    commandClass: QueryNextServerCommand
  },
{
    name: 'data/query-open',
    className: 'QueryOpenServerCommand',
    commandClass: QueryOpenServerCommand
  },
{
    name: 'data/read',
    className: 'DataReadServerCommand',
    commandClass: DataReadServerCommand
  },
{
    name: 'data/schema',
    className: 'DataSchemaServerCommand',
    commandClass: DataSchemaServerCommand
  },
{
    name: 'data/truncate',
    className: 'DataTruncateServerCommand',
    commandClass: DataTruncateServerCommand
  },
{
    name: 'data/update',
    className: 'DataUpdateServerCommand',
    commandClass: DataUpdateServerCommand
  },
{
    name: 'data/vector-search',
    className: 'VectorSearchServerCommand',
    commandClass: VectorSearchServerCommand
  },
{
    name: 'dev/activity',
    className: 'DevActivityServerCommand',
    commandClass: DevActivityServerCommand
  },
{
    name: 'dev/build-feature',
    className: 'DevBuildFeatureServerCommand',
    commandClass: DevBuildFeatureServerCommand
  },
{
    name: 'dev/code-review',
    className: 'DevCodeReviewServerCommand',
    commandClass: DevCodeReviewServerCommand
  },
{
    name: 'dev/fix-bug',
    className: 'DevFixBugServerCommand',
    commandClass: DevFixBugServerCommand
  },
{
    name: 'dev/init',
    className: 'DevInitServerCommand',
    commandClass: DevInitServerCommand
  },
{
    name: 'dev/integrate',
    className: 'DevIntegrateServerCommand',
    commandClass: DevIntegrateServerCommand
  },
{
    name: 'development/benchmark-vectors',
    className: 'BenchmarkVectorsServerCommand',
    commandClass: BenchmarkVectorsServerCommand
  },
{
    name: 'development/build',
    className: 'DevelopmentBuildServerCommand',
    commandClass: DevelopmentBuildServerCommand
  },
{
    name: 'development/code-smell',
    className: 'DevelopmentCodeSmellServerCommand',
    commandClass: DevelopmentCodeSmellServerCommand
  },
{
    name: 'development/compile-typescript',
    className: 'CompileTypescriptServerCommand',
    commandClass: CompileTypescriptServerCommand
  },
{
    name: 'development/debug/artifacts-check',
    className: 'ArtifactsCheckServerCommand',
    commandClass: ArtifactsCheckServerCommand
  },
{
    name: 'development/debug/chat-send',
    className: 'ChatSendDebugServerCommand',
    commandClass: ChatSendDebugServerCommand
  },
{
    name: 'development/debug/crud-sync',
    className: 'CrudSyncServerCommand',
    commandClass: CrudSyncServerCommand
  },
{
    name: 'development/debug/error',
    className: 'DebugErrorServerCommand',
    commandClass: DebugErrorServerCommand
  },
{
    name: 'development/debug/html-inspector',
    className: 'HtmlInspectorServerCommand',
    commandClass: HtmlInspectorServerCommand
  },
{
    name: 'development/debug/scroll-test',
    className: 'ScrollTestServerCommand',
    commandClass: ScrollTestServerCommand
  },
{
    name: 'development/debug/widget-css',
    className: 'WidgetCSSServerCommand',
    commandClass: WidgetCSSServerCommand
  },
{
    name: 'development/debug/widget-events',
    className: 'WidgetEventsDebugServerCommand',
    commandClass: WidgetEventsDebugServerCommand
  },
{
    name: 'development/debug/widget-interact',
    className: 'WidgetInteractServerCommand',
    commandClass: WidgetInteractServerCommand
  },
{
    name: 'development/debug/widget-state',
    className: 'WidgetStateServerCommand',
    commandClass: WidgetStateServerCommand
  },
{
    name: 'development/exec',
    className: 'ExecServerCommand',
    commandClass: ExecServerCommand
  },
{
    name: 'development/generate/audit',
    className: 'DevelopmentGenerateAuditServerCommand',
    commandClass: DevelopmentGenerateAuditServerCommand
  },
{
    name: 'development/generate/help',
    className: 'DevelopmentGenerateHelpServerCommand',
    commandClass: DevelopmentGenerateHelpServerCommand
  },
{
    name: 'development/generate/reverse',
    className: 'DevelopmentGenerateReverseServerCommand',
    commandClass: DevelopmentGenerateReverseServerCommand
  },
{
    name: 'development/generate',
    className: 'GenerateServerCommand',
    commandClass: GenerateServerCommand
  },
{
    name: 'development/propose-command',
    className: 'ProposeCommandServerCommand',
    commandClass: ProposeCommandServerCommand
  },
{
    name: 'development/sandbox-execute',
    className: 'SandboxExecuteServerCommand',
    commandClass: SandboxExecuteServerCommand
  },
{
    name: 'development/schema/generate',
    className: 'SchemaGenerateServerCommand',
    commandClass: SchemaGenerateServerCommand
  },
{
    name: 'development/shell/execute',
    className: 'ShellExecuteServerCommand',
    commandClass: ShellExecuteServerCommand
  },
{
    name: 'development/timing',
    className: 'TimingServerCommand',
    commandClass: TimingServerCommand
  },
{
    name: 'development/verify-web',
    className: 'DevelopmentVerifyWebServerCommand',
    commandClass: DevelopmentVerifyWebServerCommand
  },
{
    name: 'file/append',
    className: 'FileAppendServerCommand',
    commandClass: FileAppendServerCommand
  },
{
    name: 'file/load',
    className: 'FileLoadServerCommand',
    commandClass: FileLoadServerCommand
  },
{
    name: 'file/mime-type',
    className: 'FileMimeTypeServerCommand',
    commandClass: FileMimeTypeServerCommand
  },
{
    name: 'file/save',
    className: 'FileSaveServerCommand',
    commandClass: FileSaveServerCommand
  },
{
    name: 'genome/academy-competition',
    className: 'GenomeAcademyCompetitionServerCommand',
    commandClass: GenomeAcademyCompetitionServerCommand
  },
{
    name: 'genome/academy-session-detail',
    className: 'GenomeAcademySessionDetailServerCommand',
    commandClass: GenomeAcademySessionDetailServerCommand
  },
{
    name: 'genome/academy-session-list',
    className: 'GenomeAcademySessionListServerCommand',
    commandClass: GenomeAcademySessionListServerCommand
  },
{
    name: 'genome/academy-session-restart',
    className: 'GenomeAcademySessionRestartServerCommand',
    commandClass: GenomeAcademySessionRestartServerCommand
  },
{
    name: 'genome/academy-session',
    className: 'GenomeAcademySessionServerCommand',
    commandClass: GenomeAcademySessionServerCommand
  },
{
    name: 'genome/adapter-backfill-metrics',
    className: 'GenomeAdapterBackfillMetricsServerCommand',
    commandClass: GenomeAdapterBackfillMetricsServerCommand
  },
{
    name: 'genome/adapter-info',
    className: 'GenomeAdapterInfoServerCommand',
    commandClass: GenomeAdapterInfoServerCommand
  },
{
    name: 'genome/adapter-list',
    className: 'GenomeAdapterListServerCommand',
    commandClass: GenomeAdapterListServerCommand
  },
{
    name: 'genome/adapter-prune',
    className: 'GenomeAdapterPruneServerCommand',
    commandClass: GenomeAdapterPruneServerCommand
  },
{
    name: 'genome/adapter-update-metrics',
    className: 'GenomeAdapterUpdateMetricsServerCommand',
    commandClass: GenomeAdapterUpdateMetricsServerCommand
  },
{
    name: 'genome/batch-micro-tune',
    className: 'GenomeBatchMicroTuneServerCommand',
    commandClass: GenomeBatchMicroTuneServerCommand
  },
{
    name: 'genome/benchmark',
    className: 'GenomeBenchmarkServerCommand',
    commandClass: GenomeBenchmarkServerCommand
  },
{
    name: 'genome/compose',
    className: 'GenomeComposeServerCommand',
    commandClass: GenomeComposeServerCommand
  },
{
    name: 'genome/convert',
    className: 'GenomeConvertServerCommand',
    commandClass: GenomeConvertServerCommand
  },
{
    name: 'genome/dataset-import',
    className: 'GenomeDatasetImportServerCommand',
    commandClass: GenomeDatasetImportServerCommand
  },
{
    name: 'genome/dataset-prepare',
    className: 'GenomeDatasetPrepareServerCommand',
    commandClass: GenomeDatasetPrepareServerCommand
  },
{
    name: 'genome/dataset-synthesize',
    className: 'GenomeDatasetSynthesizeServerCommand',
    commandClass: GenomeDatasetSynthesizeServerCommand
  },
{
    name: 'genome/demo-run',
    className: 'GenomeDemoRunServerCommand',
    commandClass: GenomeDemoRunServerCommand
  },
{
    name: 'genome/gap-analysis',
    className: 'GenomeGapAnalysisServerCommand',
    commandClass: GenomeGapAnalysisServerCommand
  },
{
    name: 'genome/job-create',
    className: 'GenomeJobCreateServerCommand',
    commandClass: GenomeJobCreateServerCommand
  },
{
    name: 'genome/job-status',
    className: 'GenomeJobStatusServerCommand',
    commandClass: GenomeJobStatusServerCommand
  },
{
    name: 'genome/layers',
    className: 'GenomeLayersServerCommand',
    commandClass: GenomeLayersServerCommand
  },
{
    name: 'genome/paging-activate',
    className: 'GenomeActivateServerCommand',
    commandClass: GenomeActivateServerCommand
  },
{
    name: 'genome/paging-adapter-register',
    className: 'GenomePagingAdapterRegisterServerCommand',
    commandClass: GenomePagingAdapterRegisterServerCommand
  },
{
    name: 'genome/paging-deactivate',
    className: 'GenomeDeactivateServerCommand',
    commandClass: GenomeDeactivateServerCommand
  },
{
    name: 'genome/paging-register',
    className: 'GenomeRegisterServerCommand',
    commandClass: GenomeRegisterServerCommand
  },
{
    name: 'genome/paging-stats',
    className: 'GenomePagingStatsServerCommand',
    commandClass: GenomePagingStatsServerCommand
  },
{
    name: 'genome/paging-unregister',
    className: 'GenomeUnregisterServerCommand',
    commandClass: GenomeUnregisterServerCommand
  },
{
    name: 'genome/phenotype-validate',
    className: 'GenomePhenotypeValidateServerCommand',
    commandClass: GenomePhenotypeValidateServerCommand
  },
{
    name: 'genome/train/list-jobs',
    className: 'GenomeTrainListJobsServerCommand',
    commandClass: GenomeTrainListJobsServerCommand
  },
{
    name: 'genome/train/resume',
    className: 'GenomeTrainResumeServerCommand',
    commandClass: GenomeTrainResumeServerCommand
  },
{
    name: 'genome/train',
    className: 'GenomeTrainServerCommand',
    commandClass: GenomeTrainServerCommand
  },
{
    name: 'genome/training-export',
    className: 'GenomeTrainingExportServerCommand',
    commandClass: GenomeTrainingExportServerCommand
  },
{
    name: 'genome/training-overview',
    className: 'GenomeTrainingOverviewServerCommand',
    commandClass: GenomeTrainingOverviewServerCommand
  },
{
    name: 'genome/training-pipeline',
    className: 'GenomeTrainingPipelineServerCommand',
    commandClass: GenomeTrainingPipelineServerCommand
  },
{
    name: 'gpu/stats',
    className: 'GpuStatsServerCommand',
    commandClass: GpuStatsServerCommand
  },
{
    name: 'grid/audit',
    className: 'GridAuditServerCommand',
    commandClass: GridAuditServerCommand
  },
{
    name: 'grid/deploy',
    className: 'GridDeployServerCommand',
    commandClass: GridDeployServerCommand
  },
{
    name: 'grid/discover',
    className: 'GridDiscoverServerCommand',
    commandClass: GridDiscoverServerCommand
  },
{
    name: 'grid/job-control',
    className: 'GridJobControlServerCommand',
    commandClass: GridJobControlServerCommand
  },
{
    name: 'grid/job-queue',
    className: 'GridJobQueueServerCommand',
    commandClass: GridJobQueueServerCommand
  },
{
    name: 'grid/job-submit',
    className: 'GridJobSubmitServerCommand',
    commandClass: GridJobSubmitServerCommand
  },
{
    name: 'grid/node-status',
    className: 'GridNodeStatusServerCommand',
    commandClass: GridNodeStatusServerCommand
  },
{
    name: 'grid/nodes',
    className: 'GridNodesServerCommand',
    commandClass: GridNodesServerCommand
  },
{
    name: 'grid/pair',
    className: 'GridPairServerCommand',
    commandClass: GridPairServerCommand
  },
{
    name: 'grid/ping',
    className: 'GridPingServerCommand',
    commandClass: GridPingServerCommand
  },
{
    name: 'grid/route',
    className: 'GridRouteServerCommand',
    commandClass: GridRouteServerCommand
  },
{
    name: 'grid/send',
    className: 'GridSendServerCommand',
    commandClass: GridSendServerCommand
  },
{
    name: 'grid/setup-check',
    className: 'GridSetupCheckServerCommand',
    commandClass: GridSetupCheckServerCommand
  },
{
    name: 'grid/status',
    className: 'GridStatusServerCommand',
    commandClass: GridStatusServerCommand
  },
{
    name: 'grid/trust',
    className: 'GridTrustServerCommand',
    commandClass: GridTrustServerCommand
  },
{
    name: 'help',
    className: 'HelpServerCommand',
    commandClass: HelpServerCommand
  },
{
    name: 'indicator',
    className: 'IndicatorServerCommand',
    commandClass: IndicatorServerCommand
  },
{
    name: 'inference/capacity',
    className: 'InferenceCapacityServerCommand',
    commandClass: InferenceCapacityServerCommand
  },
{
    name: 'inference/generate',
    className: 'InferenceGenerateServerCommand',
    commandClass: InferenceGenerateServerCommand
  },
{
    name: 'interface/browser/capabilities',
    className: 'InterfaceBrowserCapabilitiesServerCommand',
    commandClass: InterfaceBrowserCapabilitiesServerCommand
  },
{
    name: 'interface/click',
    className: 'ClickServerCommand',
    commandClass: ClickServerCommand
  },
{
    name: 'interface/get-text',
    className: 'GetTextServerCommand',
    commandClass: GetTextServerCommand
  },
{
    name: 'interface/interact',
    className: 'InterfaceInteractServerCommand',
    commandClass: InterfaceInteractServerCommand
  },
{
    name: 'interface/launch/url',
    className: 'InterfaceLaunchUrlServerCommand',
    commandClass: InterfaceLaunchUrlServerCommand
  },
{
    name: 'interface/navigate',
    className: 'NavigateServerCommand',
    commandClass: NavigateServerCommand
  },
{
    name: 'interface/page/fill',
    className: 'InterfacePageFillServerCommand',
    commandClass: InterfacePageFillServerCommand
  },
{
    name: 'interface/page/forms',
    className: 'InterfacePageFormsServerCommand',
    commandClass: InterfacePageFormsServerCommand
  },
{
    name: 'interface/page/submit',
    className: 'InterfacePageSubmitServerCommand',
    commandClass: InterfacePageSubmitServerCommand
  },
{
    name: 'interface/proxy-navigate',
    className: 'ProxyNavigateServerCommand',
    commandClass: ProxyNavigateServerCommand
  },
{
    name: 'interface/screenshot',
    className: 'ScreenshotServerCommand',
    commandClass: ScreenshotServerCommand
  },
{
    name: 'interface/scroll',
    className: 'ScrollServerCommand',
    commandClass: ScrollServerCommand
  },
{
    name: 'interface/type',
    className: 'TypeServerCommand',
    commandClass: TypeServerCommand
  },
{
    name: 'interface/wait-for-element',
    className: 'WaitForElementServerCommand',
    commandClass: WaitForElementServerCommand
  },
{
    name: 'interface/web/fetch',
    className: 'WebFetchServerCommand',
    commandClass: WebFetchServerCommand
  },
{
    name: 'interface/web/search',
    className: 'WebSearchServerCommand',
    commandClass: WebSearchServerCommand
  },
{
    name: 'interface/webmcp/call',
    className: 'InterfaceWebmcpCallServerCommand',
    commandClass: InterfaceWebmcpCallServerCommand
  },
{
    name: 'interface/webmcp/discover',
    className: 'InterfaceWebmcpDiscoverServerCommand',
    commandClass: InterfaceWebmcpDiscoverServerCommand
  },
{
    name: 'list',
    className: 'ListServerCommand',
    commandClass: ListServerCommand
  },
{
    name: 'logging/disable',
    className: 'LoggingDisableServerCommand',
    commandClass: LoggingDisableServerCommand
  },
{
    name: 'logging/enable',
    className: 'LoggingEnableServerCommand',
    commandClass: LoggingEnableServerCommand
  },
{
    name: 'logging/status',
    className: 'LoggingStatusServerCommand',
    commandClass: LoggingStatusServerCommand
  },
{
    name: 'logs/config',
    className: 'LogsConfigServerCommand',
    commandClass: LogsConfigServerCommand
  },
{
    name: 'logs/list',
    className: 'LogsListServerCommand',
    commandClass: LogsListServerCommand
  },
{
    name: 'logs/read',
    className: 'LogsReadServerCommand',
    commandClass: LogsReadServerCommand
  },
{
    name: 'logs/search',
    className: 'LogsSearchServerCommand',
    commandClass: LogsSearchServerCommand
  },
{
    name: 'logs/stats',
    className: 'LogsStatsServerCommand',
    commandClass: LogsStatsServerCommand
  },
{
    name: 'media/prewarm',
    className: 'MediaPrewarmServerCommand',
    commandClass: MediaPrewarmServerCommand
  },
{
    name: 'media/process',
    className: 'MediaProcessServerCommand',
    commandClass: MediaProcessServerCommand
  },
{
    name: 'media/resize',
    className: 'MediaResizeServerCommand',
    commandClass: MediaResizeServerCommand
  },
{
    name: 'migration/cutover',
    className: 'MigrationCutoverServerCommand',
    commandClass: MigrationCutoverServerCommand
  },
{
    name: 'migration/pause',
    className: 'MigrationPauseServerCommand',
    commandClass: MigrationPauseServerCommand
  },
{
    name: 'migration/resume',
    className: 'MigrationResumeServerCommand',
    commandClass: MigrationResumeServerCommand
  },
{
    name: 'migration/rollback',
    className: 'MigrationRollbackServerCommand',
    commandClass: MigrationRollbackServerCommand
  },
{
    name: 'migration/start',
    className: 'MigrationStartServerCommand',
    commandClass: MigrationStartServerCommand
  },
{
    name: 'migration/status',
    className: 'MigrationStatusServerCommand',
    commandClass: MigrationStatusServerCommand
  },
{
    name: 'migration/verify',
    className: 'MigrationVerifyServerCommand',
    commandClass: MigrationVerifyServerCommand
  },
{
    name: 'model/download',
    className: 'ModelDownloadServerCommand',
    commandClass: ModelDownloadServerCommand
  },
{
    name: 'model/forge-status',
    className: 'ModelForgeStatusServerCommand',
    commandClass: ModelForgeStatusServerCommand
  },
{
    name: 'model/forge',
    className: 'ModelForgeServerCommand',
    commandClass: ModelForgeServerCommand
  },
{
    name: 'model/introspect',
    className: 'ModelIntrospectServerCommand',
    commandClass: ModelIntrospectServerCommand
  },
{
    name: 'model/list-published',
    className: 'ModelListPublishedServerCommand',
    commandClass: ModelListPublishedServerCommand
  },
{
    name: 'model/publish',
    className: 'ModelPublishServerCommand',
    commandClass: ModelPublishServerCommand
  },
{
    name: 'model/search',
    className: 'ModelSearchServerCommand',
    commandClass: ModelSearchServerCommand
  },
{
    name: 'ontology/bridge/translate',
    className: 'OntologyBridgeTranslateServerCommand',
    commandClass: OntologyBridgeTranslateServerCommand
  },
{
    name: 'ontology/concept/lookup-batch',
    className: 'OntologyConceptLookupBatchServerCommand',
    commandClass: OntologyConceptLookupBatchServerCommand
  },
{
    name: 'persona/allocate',
    className: 'PersonaAllocateServerCommand',
    commandClass: PersonaAllocateServerCommand
  },
{
    name: 'persona/genome',
    className: 'PersonaGenomeServerCommand',
    commandClass: PersonaGenomeServerCommand
  },
{
    name: 'persona/learning/capture-feedback',
    className: 'GenomeCaptureFeedbackServerCommand',
    commandClass: GenomeCaptureFeedbackServerCommand
  },
{
    name: 'persona/learning/capture-interaction',
    className: 'GenomeCaptureInteractionServerCommand',
    commandClass: GenomeCaptureInteractionServerCommand
  },
{
    name: 'persona/learning/multi-agent-learn',
    className: 'GenomeMultiAgentLearnServerCommand',
    commandClass: GenomeMultiAgentLearnServerCommand
  },
{
    name: 'persona/learning/pattern/capture',
    className: 'PersonaLearningPatternCaptureServerCommand',
    commandClass: PersonaLearningPatternCaptureServerCommand
  },
{
    name: 'persona/learning/pattern/endorse',
    className: 'PersonaLearningPatternEndorseServerCommand',
    commandClass: PersonaLearningPatternEndorseServerCommand
  },
{
    name: 'persona/learning/pattern/query',
    className: 'PersonaLearningPatternQueryServerCommand',
    commandClass: PersonaLearningPatternQueryServerCommand
  },
{
    name: 'ping',
    className: 'PingServerCommand',
    commandClass: PingServerCommand
  },
{
    name: 'plasticity/analyze',
    className: 'PlasticityAnalyzeServerCommand',
    commandClass: PlasticityAnalyzeServerCommand
  },
{
    name: 'plasticity/compact',
    className: 'PlasticityCompactServerCommand',
    commandClass: PlasticityCompactServerCommand
  },
{
    name: 'plasticity/compress',
    className: 'PlasticityCompressServerCommand',
    commandClass: PlasticityCompressServerCommand
  },
{
    name: 'plasticity/pipeline',
    className: 'PlasticityPipelineServerCommand',
    commandClass: PlasticityPipelineServerCommand
  },
{
    name: 'plasticity/topology',
    className: 'PlasticityTopologyServerCommand',
    commandClass: PlasticityTopologyServerCommand
  },
{
    name: 'positron/cursor',
    className: 'PositronCursorServerCommand',
    commandClass: PositronCursorServerCommand
  },
{
    name: 'process-registry',
    className: 'ProcessRegistryServerCommand',
    commandClass: ProcessRegistryServerCommand
  },
{
    name: 'rag/budget',
    className: 'RAGBudgetServerCommand',
    commandClass: RAGBudgetServerCommand
  },
{
    name: 'rag/load',
    className: 'RAGLoadServerCommand',
    commandClass: RAGLoadServerCommand
  },
{
    name: 'recipe/generate',
    className: 'RecipeGenerateServerCommand',
    commandClass: RecipeGenerateServerCommand
  },
{
    name: 'recipe/list',
    className: 'RecipeListServerCommand',
    commandClass: RecipeListServerCommand
  },
{
    name: 'recipe/run',
    className: 'RecipeRunServerCommand',
    commandClass: RecipeRunServerCommand
  },
{
    name: 'runtime/metrics',
    className: 'RuntimeMetricsServerCommand',
    commandClass: RuntimeMetricsServerCommand
  },
{
    name: 'search/execute',
    className: 'SearchExecuteServerCommand',
    commandClass: SearchExecuteServerCommand
  },
{
    name: 'search/list',
    className: 'SearchListServerCommand',
    commandClass: SearchListServerCommand
  },
{
    name: 'search/params',
    className: 'SearchParamsServerCommand',
    commandClass: SearchParamsServerCommand
  },
{
    name: 'search/vector',
    className: 'SearchVectorServerCommand',
    commandClass: SearchVectorServerCommand
  },
{
    name: 'security/setup',
    className: 'SecuritySetupServerCommand',
    commandClass: SecuritySetupServerCommand
  },
{
    name: 'sentinel/approve',
    className: 'SentinelApproveServerCommand',
    commandClass: SentinelApproveServerCommand
  },
{
    name: 'sentinel/cancel',
    className: 'SentinelCancelServerCommand',
    commandClass: SentinelCancelServerCommand
  },
{
    name: 'sentinel/cleanup',
    className: 'SentinelCleanupServerCommand',
    commandClass: SentinelCleanupServerCommand
  },
{
    name: 'sentinel/coding-agent',
    className: 'SentinelCodingAgentServerCommand',
    commandClass: SentinelCodingAgentServerCommand
  },
{
    name: 'sentinel/escalate',
    className: 'SentinelEscalateServerCommand',
    commandClass: SentinelEscalateServerCommand
  },
{
    name: 'sentinel/extend-budget',
    className: 'SentinelExtendBudgetServerCommand',
    commandClass: SentinelExtendBudgetServerCommand
  },
{
    name: 'sentinel/list',
    className: 'SentinelListServerCommand',
    commandClass: SentinelListServerCommand
  },
{
    name: 'sentinel/load',
    className: 'SentinelLoadServerCommand',
    commandClass: SentinelLoadServerCommand
  },
{
    name: 'sentinel/logs/list',
    className: 'SentinelLogsListServerCommand',
    commandClass: SentinelLogsListServerCommand
  },
{
    name: 'sentinel/logs/read',
    className: 'SentinelLogsReadServerCommand',
    commandClass: SentinelLogsReadServerCommand
  },
{
    name: 'sentinel/logs/tail',
    className: 'SentinelLogsTailServerCommand',
    commandClass: SentinelLogsTailServerCommand
  },
{
    name: 'sentinel/resume',
    className: 'SentinelResumeServerCommand',
    commandClass: SentinelResumeServerCommand
  },
{
    name: 'sentinel/run',
    className: 'SentinelRunServerCommand',
    commandClass: SentinelRunServerCommand
  },
{
    name: 'sentinel/save',
    className: 'SentinelSaveServerCommand',
    commandClass: SentinelSaveServerCommand
  },
{
    name: 'sentinel/status',
    className: 'SentinelStatusServerCommand',
    commandClass: SentinelStatusServerCommand
  },
{
    name: 'sentinel/web-research',
    className: 'SentinelWebResearchServerCommand',
    commandClass: SentinelWebResearchServerCommand
  },
{
    name: 'session/create',
    className: 'SessionCreateServerCommand',
    commandClass: SessionCreateServerCommand
  },
{
    name: 'session/destroy',
    className: 'SessionDestroyServerCommand',
    commandClass: SessionDestroyServerCommand
  },
{
    name: 'session/get-id',
    className: 'SessionGetIdServerCommand',
    commandClass: SessionGetIdServerCommand
  },
{
    name: 'session/get-user',
    className: 'SessionGetUserServerCommand',
    commandClass: SessionGetUserServerCommand
  },
{
    name: 'skill/activate',
    className: 'SkillActivateServerCommand',
    commandClass: SkillActivateServerCommand
  },
{
    name: 'skill/generate',
    className: 'SkillGenerateServerCommand',
    commandClass: SkillGenerateServerCommand
  },
{
    name: 'skill/list',
    className: 'SkillListServerCommand',
    commandClass: SkillListServerCommand
  },
{
    name: 'skill/propose',
    className: 'SkillProposeServerCommand',
    commandClass: SkillProposeServerCommand
  },
{
    name: 'skill/validate',
    className: 'SkillValidateServerCommand',
    commandClass: SkillValidateServerCommand
  },
{
    name: 'state/content/close',
    className: 'StateContentCloseServerCommand',
    commandClass: StateContentCloseServerCommand
  },
{
    name: 'state/content/switch',
    className: 'StateContentSwitchServerCommand',
    commandClass: StateContentSwitchServerCommand
  },
{
    name: 'state/create',
    className: 'StateCreateServerCommand',
    commandClass: StateCreateServerCommand
  },
{
    name: 'state/get',
    className: 'StateGetServerCommand',
    commandClass: StateGetServerCommand
  },
{
    name: 'state/update',
    className: 'StateUpdateServerCommand',
    commandClass: StateUpdateServerCommand
  },
{
    name: 'system/daemons',
    className: 'DaemonsServerCommand',
    commandClass: DaemonsServerCommand
  },
{
    name: 'system/docker-tier-stats',
    className: 'SystemDockerTierStatsServerCommand',
    commandClass: SystemDockerTierStatsServerCommand
  },
{
    name: 'system/metrics',
    className: 'SystemMetricsServerCommand',
    commandClass: SystemMetricsServerCommand
  },
{
    name: 'system/resources',
    className: 'SystemResourcesServerCommand',
    commandClass: SystemResourcesServerCommand
  },
{
    name: 'theme/get',
    className: 'ThemeGetServerCommand',
    commandClass: ThemeGetServerCommand
  },
{
    name: 'theme/list',
    className: 'ThemeListServerCommand',
    commandClass: ThemeListServerCommand
  },
{
    name: 'theme/set',
    className: 'ThemeSetServerCommand',
    commandClass: ThemeSetServerCommand
  },
{
    name: 'training/import',
    className: 'TrainingImportServerCommand',
    commandClass: TrainingImportServerCommand
  },
{
    name: 'user/create',
    className: 'UserCreateServerCommand',
    commandClass: UserCreateServerCommand
  },
{
    name: 'user/get-me',
    className: 'UserGetMeServerCommand',
    commandClass: UserGetMeServerCommand
  },
{
    name: 'user/list',
    className: 'UserListServerCommand',
    commandClass: UserListServerCommand
  },
{
    name: 'utilities/docs/list',
    className: 'DocsListServerCommand',
    commandClass: DocsListServerCommand
  },
{
    name: 'utilities/docs/read',
    className: 'DocsReadServerCommand',
    commandClass: DocsReadServerCommand
  },
{
    name: 'utilities/docs/search',
    className: 'DocsSearchServerCommand',
    commandClass: DocsSearchServerCommand
  },
{
    name: 'utilities/hello',
    className: 'HelloServerCommand',
    commandClass: HelloServerCommand
  },
{
    name: 'utilities/pipe/chain',
    className: 'PipeChainServerCommand',
    commandClass: PipeChainServerCommand
  },
{
    name: 'voice/snapshot-participant',
    className: 'VoiceSnapshotParticipantServerCommand',
    commandClass: VoiceSnapshotParticipantServerCommand
  },
{
    name: 'voice/snapshot-room',
    className: 'VoiceSnapshotRoomServerCommand',
    commandClass: VoiceSnapshotRoomServerCommand
  },
{
    name: 'voice/start',
    className: 'VoiceStartServerCommand',
    commandClass: VoiceStartServerCommand
  },
{
    name: 'voice/stop',
    className: 'VoiceStopServerCommand',
    commandClass: VoiceStopServerCommand
  },
{
    name: 'voice/synthesize',
    className: 'VoiceSynthesizeServerCommand',
    commandClass: VoiceSynthesizeServerCommand
  },
{
    name: 'voice/transcribe',
    className: 'VoiceTranscribeServerCommand',
    commandClass: VoiceTranscribeServerCommand
  },
{
    name: 'workspace/git/commit',
    className: 'GitCommitServerCommand',
    commandClass: GitCommitServerCommand
  },
{
    name: 'workspace/git/push',
    className: 'GitPushServerCommand',
    commandClass: GitPushServerCommand
  },
{
    name: 'workspace/git/status',
    className: 'GitStatusServerCommand',
    commandClass: GitStatusServerCommand
  },
{
    name: 'workspace/git/workspace/clean',
    className: 'GitWorkspaceCleanServerCommand',
    commandClass: GitWorkspaceCleanServerCommand
  },
{
    name: 'workspace/git/workspace/init',
    className: 'GitWorkspaceInitServerCommand',
    commandClass: GitWorkspaceInitServerCommand
  },
{
    name: 'image/generate-realistic',
    className: 'ImageGenerateRealisticServerCommand',
    commandClass: ImageGenerateRealisticServerCommand
  },
{
    name: 'workspace/list',
    className: 'WorkspaceListServerCommand',
    commandClass: WorkspaceListServerCommand
  },
{
    name: 'workspace/recipe/load',
    className: 'RecipeLoadServerCommand',
    commandClass: RecipeLoadServerCommand
  },
{
    name: 'workspace/task/complete',
    className: 'TaskCompleteServerCommand',
    commandClass: TaskCompleteServerCommand
  },
{
    name: 'workspace/task/create',
    className: 'TaskCreateServerCommand',
    commandClass: TaskCreateServerCommand
  },
{
    name: 'workspace/task/list',
    className: 'TaskListServerCommand',
    commandClass: TaskListServerCommand
  },
{
    name: 'workspace/tree',
    className: 'TreeServerCommand',
    commandClass: TreeServerCommand
  }
];

export const SERVER_ADAPTERS: AdapterEntry[] = [
{
    name: 'u-d-p-multicast-transport-server',
    className: 'UDPMulticastTransportServer',
    adapterClass: UDPMulticastTransportServer,
    protocol: 'websocket', // TODO: Extract from transport type
    supportedRoles: ['client', 'server'], // TODO: Extract from class metadata
    supportedEnvironments: ['{env}'] // Current environment
  },
{
    name: 'web-socket-transport-client-server',
    className: 'WebSocketTransportClientServer',
    adapterClass: WebSocketTransportClientServer,
    protocol: 'websocket', // TODO: Extract from transport type
    supportedRoles: ['client', 'server'], // TODO: Extract from class metadata
    supportedEnvironments: ['{env}'] // Current environment
  },
{
    name: 'web-socket-transport-server',
    className: 'WebSocketTransportServer',
    adapterClass: WebSocketTransportServer,
    protocol: 'websocket', // TODO: Extract from transport type
    supportedRoles: ['client', 'server'], // TODO: Extract from class metadata
    supportedEnvironments: ['{env}'] // Current environment
  }
];
