/**
 * Browser Structure Registry - Auto-generated
 *
 * Contains 11 daemons and 284 commands and 2 adapters and 37 widgets.
 * Generated by scripts/generate-structure.ts - DO NOT EDIT MANUALLY
 */

// Browser daemons Imports
import { ArchiveDaemonBrowser } from './../daemons/archive-daemon/browser/ArchiveDaemonBrowser';
import { ArtifactsDaemonBrowser } from './../daemons/artifacts-daemon/browser/ArtifactsDaemonBrowser';
import { CommandDaemonBrowser } from './../daemons/command-daemon/browser/CommandDaemonBrowser';
import { ConsoleDaemonBrowser } from './../daemons/console-daemon/browser/ConsoleDaemonBrowser';
import { DataDaemonBrowser } from './../daemons/data-daemon/browser/DataDaemonBrowser';
import { EventsDaemonBrowser } from './../daemons/events-daemon/browser/EventsDaemonBrowser';
import { HealthDaemonBrowser } from './../daemons/health-daemon/browser/HealthDaemonBrowser';
import { LoggerDaemonBrowser } from './../daemons/logger-daemon/browser/LoggerDaemonBrowser';
import { SessionDaemonBrowser } from './../daemons/session-daemon/browser/SessionDaemonBrowser';
import { UserDaemonBrowser } from './../daemons/user-daemon/browser/UserDaemonBrowser';
import { WidgetDaemonBrowser } from './../daemons/widget-daemon/browser/WidgetDaemonBrowser';

// Browser commands Imports
import { AdapterAdoptBrowserCommand } from './../commands/adapter/adopt/browser/AdapterAdoptBrowserCommand';
import { AdapterPublishBrowserCommand } from './../commands/adapter/publish/browser/AdapterPublishBrowserCommand';
import { AdapterSearchBrowserCommand } from './../commands/adapter/search/browser/AdapterSearchBrowserCommand';
import { AdapterTryBrowserCommand } from './../commands/adapter/try/browser/AdapterTryBrowserCommand';
import { AgentListBrowserCommand } from './../commands/agent/list/browser/AgentListBrowserCommand';
import { AgentStartBrowserCommand } from './../commands/agent/start/browser/AgentStartBrowserCommand';
import { AgentStatusBrowserCommand } from './../commands/agent/status/browser/AgentStatusBrowserCommand';
import { AgentStopBrowserCommand } from './../commands/agent/stop/browser/AgentStopBrowserCommand';
import { AiAgentBrowserCommand } from './../commands/ai/agent/browser/AiAgentBrowserCommand';
import { BagOfWordsBrowserCommand } from './../commands/ai/bag-of-words/browser/BagOfWordsBrowserCommand';
import { AiContextSearchBrowserCommand } from './../commands/ai/context/search/browser/AiContextSearchBrowserCommand';
import { AiContextSliceBrowserCommand } from './../commands/ai/context/slice/browser/AiContextSliceBrowserCommand';
import { AICostBrowserCommand } from './../commands/ai/cost/browser/AICostBrowserCommand';
import { AiDetectSemanticLoopBrowserCommand } from './../commands/ai/detect-semantic-loop/browser/AiDetectSemanticLoopBrowserCommand';
import { AIGenerateBrowserCommand } from './../commands/ai/generate/browser/AIGenerateBrowserCommand';
import { GenomeStatsBrowserCommand } from './../commands/ai/genome/stats/browser/GenomeStatsBrowserCommand';
import { AiKeyDiffBrowserCommand } from './../commands/ai/key/diff/browser/AiKeyDiffBrowserCommand';
import { AiKeyRemoveBrowserCommand } from './../commands/ai/key/remove/browser/AiKeyRemoveBrowserCommand';
import { AiKeySaveBrowserCommand } from './../commands/ai/key/save/browser/AiKeySaveBrowserCommand';
import { AiKeyStatusBrowserCommand } from './../commands/ai/key/status/browser/AiKeyStatusBrowserCommand';
import { AiKeyTestBrowserCommand } from './../commands/ai/key/test/browser/AiKeyTestBrowserCommand';
import { AiLocalInferenceStartBrowserCommand } from './../commands/ai/local-inference/start/browser/AiLocalInferenceStartBrowserCommand';
import { AiLocalInferenceStatusBrowserCommand } from './../commands/ai/local-inference/status/browser/AiLocalInferenceStatusBrowserCommand';
import { ModelFindBrowserCommand } from './../commands/ai/model/find/browser/ModelFindBrowserCommand';
import { ModelListBrowserCommand } from './../commands/ai/model/list/browser/ModelListBrowserCommand';
import { AIProvidersStatusBrowserCommand } from './../commands/ai/providers/status/browser/AIProvidersStatusBrowserCommand';
import { CodebaseIndexBrowserCommand } from './../commands/ai/rag/index-codebase/browser/CodebaseIndexBrowserCommand';
import { AIReportBrowserCommand } from './../commands/ai/report/browser/AIReportBrowserCommand';
import { ShouldRespondFastBrowserCommand } from './../commands/ai/should-respond-fast/browser/ShouldRespondFastBrowserCommand';
import { AIShouldRespondBrowserCommand } from './../commands/ai/should-respond/browser/AIShouldRespondBrowserCommand';
import { AiSleepBrowserCommand } from './../commands/ai/sleep/browser/AiSleepBrowserCommand';
import { AIStatusBrowserCommand } from './../commands/ai/status/browser/AIStatusBrowserCommand';
import { ThoughtStreamBrowserCommand } from './../commands/ai/thoughtstream/browser/ThoughtStreamBrowserCommand';
import { AIValidateResponseBrowserCommand } from './../commands/ai/validate-response/browser/AIValidateResponseBrowserCommand';
import { AircBridgeBrowserCommand } from './../commands/airc/bridge/browser/AircBridgeBrowserCommand';
import { AircSendBrowserCommand } from './../commands/airc/send/browser/AircSendBrowserCommand';
import { AvatarSnapshotBrowserCommand } from './../commands/avatar/snapshot/browser/AvatarSnapshotBrowserCommand';
import { CanvasStrokeAddBrowserCommand } from './../commands/canvas/stroke/add/browser/CanvasStrokeAddBrowserCommand';
import { CanvasStrokeListBrowserCommand } from './../commands/canvas/stroke/list/browser/CanvasStrokeListBrowserCommand';
import { CanvasVisionBrowserCommand } from './../commands/canvas/vision/browser/CanvasVisionBrowserCommand';
import { ClaudeContextBrowserCommand } from './../commands/claude/context/browser/ClaudeContextBrowserCommand';
import { ClaudeResumeBrowserCommand } from './../commands/claude/resume/browser/ClaudeResumeBrowserCommand';
import { ClaudeSnapshotBrowserCommand } from './../commands/claude/snapshot/browser/ClaudeSnapshotBrowserCommand';
import { CodeDiffBrowserCommand } from './../commands/code/diff/browser/CodeDiffBrowserCommand';
import { CodeEditBrowserCommand } from './../commands/code/edit/browser/CodeEditBrowserCommand';
import { CodeGitBrowserCommand } from './../commands/code/git/browser/CodeGitBrowserCommand';
import { CodeHistoryBrowserCommand } from './../commands/code/history/browser/CodeHistoryBrowserCommand';
import { CodeReadBrowserCommand } from './../commands/code/read/browser/CodeReadBrowserCommand';
import { CodeSearchBrowserCommand } from './../commands/code/search/browser/CodeSearchBrowserCommand';
import { CodeShellExecuteBrowserCommand } from './../commands/code/shell/execute/browser/CodeShellExecuteBrowserCommand';
import { CodeShellKillBrowserCommand } from './../commands/code/shell/kill/browser/CodeShellKillBrowserCommand';
import { CodeShellSentinelBrowserCommand } from './../commands/code/shell/sentinel/browser/CodeShellSentinelBrowserCommand';
import { CodeShellStatusBrowserCommand } from './../commands/code/shell/status/browser/CodeShellStatusBrowserCommand';
import { CodeShellWatchBrowserCommand } from './../commands/code/shell/watch/browser/CodeShellWatchBrowserCommand';
import { CodeTreeBrowserCommand } from './../commands/code/tree/browser/CodeTreeBrowserCommand';
import { CodeUndoBrowserCommand } from './../commands/code/undo/browser/CodeUndoBrowserCommand';
import { CodeVerifyBrowserCommand } from './../commands/code/verify/browser/CodeVerifyBrowserCommand';
import { CodeWriteBrowserCommand } from './../commands/code/write/browser/CodeWriteBrowserCommand';
import { CognitionAdmitInboxMessageBrowserCommand } from './../commands/cognition/admit-inbox-message/browser/CognitionAdmitInboxMessageBrowserCommand';
import { CognitionRecallEngramsBrowserCommand } from './../commands/cognition/recall-engrams/browser/CognitionRecallEngramsBrowserCommand';
import { CognitionVisionDescribeBrowserCommand } from './../commands/cognition/vision-describe/browser/CognitionVisionDescribeBrowserCommand';
import { ActivityUserPresentCommand } from './../commands/collaboration/activity/user-present/browser/ActivityUserPresentCommand';
import { ChatAnalyzeBrowserCommand } from './../commands/collaboration/chat/analyze/browser/ChatAnalyzeBrowserCommand';
import { ChatExportBrowserCommand } from './../commands/collaboration/chat/export/browser/ChatExportBrowserCommand';
import { ChatPollBrowserCommand } from './../commands/collaboration/chat/poll/browser/ChatPollBrowserCommand';
import { ChatSendBrowserCommand } from './../commands/collaboration/chat/send/browser/ChatSendBrowserCommand';
import { ContentOpenBrowserCommand } from './../commands/collaboration/content/open/browser/ContentOpenBrowserCommand';
import { DecisionCreateBrowserCommand } from './../commands/collaboration/decision/create/browser/DecisionCreateBrowserCommand';
import { DecisionFinalizeBrowserCommand } from './../commands/collaboration/decision/finalize/browser/DecisionFinalizeBrowserCommand';
import { DecisionListBrowserCommand } from './../commands/collaboration/decision/list/browser/DecisionListBrowserCommand';
import { DecisionProposeBrowserCommand } from './../commands/collaboration/decision/propose/browser/DecisionProposeBrowserCommand';
import { DecisionRankBrowserCommand } from './../commands/collaboration/decision/rank/browser/DecisionRankBrowserCommand';
import { DecisionViewBrowserCommand } from './../commands/collaboration/decision/view/browser/DecisionViewBrowserCommand';
import { DecisionVoteBrowserCommand } from './../commands/collaboration/decision/vote/browser/DecisionVoteBrowserCommand';
import { DmBrowserCommand } from './../commands/collaboration/dm/browser/DmBrowserCommand';
import { LiveJoinBrowserCommand } from './../commands/collaboration/live/join/browser/LiveJoinBrowserCommand';
import { LiveLeaveBrowserCommand } from './../commands/collaboration/live/leave/browser/LiveLeaveBrowserCommand';
import { CollaborationLiveStartBrowserCommand } from './../commands/collaboration/live/start/browser/CollaborationLiveStartBrowserCommand';
import { CollaborationLiveTranscriptionBrowserCommand } from './../commands/collaboration/live/transcription/browser/CollaborationLiveTranscriptionBrowserCommand';
import { WallListBrowserCommand } from './../commands/collaboration/wall/list/browser/WallListBrowserCommand';
import { WallReadBrowserCommand } from './../commands/collaboration/wall/read/browser/WallReadBrowserCommand';
import { WallWriteBrowserCommand } from './../commands/collaboration/wall/write/browser/WallWriteBrowserCommand';
import { EmotionBrowserCommand } from './../commands/continuum/emotion/browser/EmotionBrowserCommand';
import { ContinuumSetBrowserCommand } from './../commands/continuum/set/browser/ContinuumSetBrowserCommand';
import { BackfillVectorsBrowserCommand } from './../commands/data/backfill-vectors/browser/BackfillVectorsBrowserCommand';
import { DataClearBrowserCommand } from './../commands/data/clear/browser/DataClearBrowserCommand';
import { DataCloseBrowserCommand } from './../commands/data/close/browser/DataCloseBrowserCommand';
import { DataCreateBrowserCommand } from './../commands/data/create/browser/DataCreateBrowserCommand';
import { DataDeleteBrowserCommand } from './../commands/data/delete/browser/DataDeleteBrowserCommand';
import { GenerateEmbeddingBrowserCommand } from './../commands/data/generate-embedding/browser/GenerateEmbeddingBrowserCommand';
import { DataListHandlesBrowserCommand } from './../commands/data/list-handles/browser/DataListHandlesBrowserCommand';
import { DataListBrowserCommand } from './../commands/data/list/browser/DataListBrowserCommand';
import { DataOpenBrowserCommand } from './../commands/data/open/browser/DataOpenBrowserCommand';
import { QueryCloseBrowserCommand } from './../commands/data/query-close/browser/QueryCloseBrowserCommand';
import { QueryNextBrowserCommand } from './../commands/data/query-next/browser/QueryNextBrowserCommand';
import { QueryOpenBrowserCommand } from './../commands/data/query-open/browser/QueryOpenBrowserCommand';
import { DataReadBrowserCommand } from './../commands/data/read/browser/DataReadBrowserCommand';
import { DataSchemaBrowserCommand } from './../commands/data/schema/browser/DataSchemaBrowserCommand';
import { DataTruncateBrowserCommand } from './../commands/data/truncate/browser/DataTruncateBrowserCommand';
import { DataUpdateBrowserCommand } from './../commands/data/update/browser/DataUpdateBrowserCommand';
import { VectorSearchBrowserCommand } from './../commands/data/vector-search/browser/VectorSearchBrowserCommand';
import { DevelopmentBuildBrowserCommand } from './../commands/development/build/browser/DevelopmentBuildBrowserCommand';
import { DevelopmentCodeSmellBrowserCommand } from './../commands/development/code-smell/browser/DevelopmentCodeSmellBrowserCommand';
import { CompileTypescriptBrowserCommand } from './../commands/development/compile-typescript/browser/CompileTypescriptBrowserCommand';
import { ArtifactsCheckBrowserCommand } from './../commands/development/debug/artifacts-check/browser/ArtifactsCheckBrowserCommand';
import { ChatSendDebugBrowserCommand } from './../commands/development/debug/chat-send/browser/ChatSendDebugBrowserCommand';
import { CrudSyncBrowserCommand } from './../commands/development/debug/crud-sync/browser/CrudSyncBrowserCommand';
import { DebugErrorBrowserCommand } from './../commands/development/debug/error/browser/DebugErrorBrowserCommand';
import { HtmlInspectorBrowserCommand } from './../commands/development/debug/html-inspector/browser/HtmlInspectorBrowserCommand';
import { ScrollTestBrowserCommand } from './../commands/development/debug/scroll-test/browser/ScrollTestBrowserCommand';
import { WidgetCSSBrowserCommand } from './../commands/development/debug/widget-css/browser/WidgetCSSBrowserCommand';
import { WidgetEventsDebugBrowserCommand } from './../commands/development/debug/widget-events/browser/WidgetEventsDebugBrowserCommand';
import { WidgetInteractBrowserCommand } from './../commands/development/debug/widget-interact/browser/WidgetInteractBrowserCommand';
import { WidgetStateBrowserCommand } from './../commands/development/debug/widget-state/browser/WidgetStateBrowserCommand';
import { ExecBrowserCommand } from './../commands/development/exec/browser/ExecBrowserCommand';
import { DevelopmentGenerateAuditBrowserCommand } from './../commands/development/generate/audit/browser/DevelopmentGenerateAuditBrowserCommand';
import { GenerateBrowserCommand } from './../commands/development/generate/browser/GenerateBrowserCommand';
import { DevelopmentGenerateHelpBrowserCommand } from './../commands/development/generate/help/browser/DevelopmentGenerateHelpBrowserCommand';
import { DevelopmentGenerateReverseBrowserCommand } from './../commands/development/generate/reverse/browser/DevelopmentGenerateReverseBrowserCommand';
import { SchemaGenerateBrowserCommand } from './../commands/development/schema/generate/browser/SchemaGenerateBrowserCommand';
import { ShellExecuteBrowserCommand } from './../commands/development/shell/execute/browser/ShellExecuteBrowserCommand';
import { DevelopmentVerifyWebBrowserCommand } from './../commands/development/verify-web/browser/DevelopmentVerifyWebBrowserCommand';
import { FileAppendBrowserCommand } from './../commands/file/append/browser/FileAppendBrowserCommand';
import { FileLoadBrowserCommand } from './../commands/file/load/browser/FileLoadBrowserCommand';
import { FileMimeTypeBrowserCommand } from './../commands/file/mime-type/browser/FileMimeTypeBrowserCommand';
import { FileSaveBrowserCommand } from './../commands/file/save/browser/FileSaveBrowserCommand';
import { GenomeAcademyCompetitionBrowserCommand } from './../commands/genome/academy-competition/browser/GenomeAcademyCompetitionBrowserCommand';
import { GenomeAcademySessionDetailBrowserCommand } from './../commands/genome/academy-session-detail/browser/GenomeAcademySessionDetailBrowserCommand';
import { GenomeAcademySessionListBrowserCommand } from './../commands/genome/academy-session-list/browser/GenomeAcademySessionListBrowserCommand';
import { GenomeAcademySessionRestartBrowserCommand } from './../commands/genome/academy-session-restart/browser/GenomeAcademySessionRestartBrowserCommand';
import { GenomeAcademySessionBrowserCommand } from './../commands/genome/academy-session/browser/GenomeAcademySessionBrowserCommand';
import { GenomeAdapterBackfillMetricsBrowserCommand } from './../commands/genome/adapter-backfill-metrics/browser/GenomeAdapterBackfillMetricsBrowserCommand';
import { GenomeAdapterUpdateMetricsBrowserCommand } from './../commands/genome/adapter-update-metrics/browser/GenomeAdapterUpdateMetricsBrowserCommand';
import { GenomeBatchMicroTuneBrowserCommand } from './../commands/genome/batch-micro-tune/browser/GenomeBatchMicroTuneBrowserCommand';
import { GenomeBenchmarkBrowserCommand } from './../commands/genome/benchmark/browser/GenomeBenchmarkBrowserCommand';
import { GenomeConvertBrowserCommand } from './../commands/genome/convert/browser/GenomeConvertBrowserCommand';
import { GenomeDatasetImportBrowserCommand } from './../commands/genome/dataset-import/browser/GenomeDatasetImportBrowserCommand';
import { GenomeDatasetPrepareBrowserCommand } from './../commands/genome/dataset-prepare/browser/GenomeDatasetPrepareBrowserCommand';
import { GenomeDatasetSynthesizeBrowserCommand } from './../commands/genome/dataset-synthesize/browser/GenomeDatasetSynthesizeBrowserCommand';
import { GenomeDemoRunBrowserCommand } from './../commands/genome/demo-run/browser/GenomeDemoRunBrowserCommand';
import { GenomeJobCreateBrowserCommand } from './../commands/genome/job-create/browser/GenomeJobCreateBrowserCommand';
import { GenomeJobStatusBrowserCommand } from './../commands/genome/job-status/browser/GenomeJobStatusBrowserCommand';
import { GenomeLayersBrowserCommand } from './../commands/genome/layers/browser/GenomeLayersBrowserCommand';
import { GenomeTrainBrowserCommand } from './../commands/genome/train/browser/GenomeTrainBrowserCommand';
import { GenomeTrainListJobsBrowserCommand } from './../commands/genome/train/list-jobs/browser/GenomeTrainListJobsBrowserCommand';
import { GenomeTrainResumeBrowserCommand } from './../commands/genome/train/resume/browser/GenomeTrainResumeBrowserCommand';
import { GenomeTrainingExportBrowserCommand } from './../commands/genome/training-export/browser/GenomeTrainingExportBrowserCommand';
import { GenomeTrainingOverviewBrowserCommand } from './../commands/genome/training-overview/browser/GenomeTrainingOverviewBrowserCommand';
import { GenomeTrainingPipelineBrowserCommand } from './../commands/genome/training-pipeline/browser/GenomeTrainingPipelineBrowserCommand';
import { GpuStatsBrowserCommand } from './../commands/gpu/stats/browser/GpuStatsBrowserCommand';
import { GridAuditBrowserCommand } from './../commands/grid/audit/browser/GridAuditBrowserCommand';
import { GridDeployBrowserCommand } from './../commands/grid/deploy/browser/GridDeployBrowserCommand';
import { GridDiscoverBrowserCommand } from './../commands/grid/discover/browser/GridDiscoverBrowserCommand';
import { GridJobControlBrowserCommand } from './../commands/grid/job-control/browser/GridJobControlBrowserCommand';
import { GridJobQueueBrowserCommand } from './../commands/grid/job-queue/browser/GridJobQueueBrowserCommand';
import { GridJobSubmitBrowserCommand } from './../commands/grid/job-submit/browser/GridJobSubmitBrowserCommand';
import { GridNodeStatusBrowserCommand } from './../commands/grid/node-status/browser/GridNodeStatusBrowserCommand';
import { GridNodesBrowserCommand } from './../commands/grid/nodes/browser/GridNodesBrowserCommand';
import { GridPairBrowserCommand } from './../commands/grid/pair/browser/GridPairBrowserCommand';
import { GridPingBrowserCommand } from './../commands/grid/ping/browser/GridPingBrowserCommand';
import { GridRouteBrowserCommand } from './../commands/grid/route/browser/GridRouteBrowserCommand';
import { GridSendBrowserCommand } from './../commands/grid/send/browser/GridSendBrowserCommand';
import { GridSetupCheckBrowserCommand } from './../commands/grid/setup-check/browser/GridSetupCheckBrowserCommand';
import { GridStatusBrowserCommand } from './../commands/grid/status/browser/GridStatusBrowserCommand';
import { GridTrustBrowserCommand } from './../commands/grid/trust/browser/GridTrustBrowserCommand';
import { HelpBrowserCommand } from './../commands/help/browser/HelpBrowserCommand';
import { IndicatorBrowserCommand } from './../commands/indicator/browser/IndicatorBrowserCommand';
import { InferenceCapacityBrowserCommand } from './../commands/inference/capacity/browser/InferenceCapacityBrowserCommand';
import { InferenceGenerateBrowserCommand } from './../commands/inference/generate/browser/InferenceGenerateBrowserCommand';
import { InterfaceBrowserCapabilitiesBrowserCommand } from './../commands/interface/browser/capabilities/browser/InterfaceBrowserCapabilitiesBrowserCommand';
import { ClickBrowserCommand } from './../commands/interface/click/browser/ClickBrowserCommand';
import { GetTextBrowserCommand } from './../commands/interface/get-text/browser/GetTextBrowserCommand';
import { InterfaceInteractBrowserCommand } from './../commands/interface/interact/browser/InterfaceInteractBrowserCommand';
import { InterfaceLaunchUrlBrowserCommand } from './../commands/interface/launch/url/browser/InterfaceLaunchUrlBrowserCommand';
import { NavigateBrowserCommand } from './../commands/interface/navigate/browser/NavigateBrowserCommand';
import { InterfacePageFillBrowserCommand } from './../commands/interface/page/fill/browser/InterfacePageFillBrowserCommand';
import { InterfacePageFormsBrowserCommand } from './../commands/interface/page/forms/browser/InterfacePageFormsBrowserCommand';
import { InterfacePageSubmitBrowserCommand } from './../commands/interface/page/submit/browser/InterfacePageSubmitBrowserCommand';
import { ProxyNavigateBrowserCommand } from './../commands/interface/proxy-navigate/browser/ProxyNavigateBrowserCommand';
import { ScreenshotBrowserCommand } from './../commands/interface/screenshot/browser/ScreenshotBrowserCommand';
import { ScrollBrowserCommand } from './../commands/interface/scroll/browser/ScrollBrowserCommand';
import { TypeBrowserCommand } from './../commands/interface/type/browser/TypeBrowserCommand';
import { WaitForElementBrowserCommand } from './../commands/interface/wait-for-element/browser/WaitForElementBrowserCommand';
import { WebFetchBrowserCommand } from './../commands/interface/web/fetch/browser/WebFetchBrowserCommand';
import { InterfaceWebmcpCallBrowserCommand } from './../commands/interface/webmcp/call/browser/InterfaceWebmcpCallBrowserCommand';
import { InterfaceWebmcpDiscoverBrowserCommand } from './../commands/interface/webmcp/discover/browser/InterfaceWebmcpDiscoverBrowserCommand';
import { ListBrowserCommand } from './../commands/list/browser/ListBrowserCommand';
import { LoggingDisableBrowserCommand } from './../commands/logging/disable/browser/LoggingDisableBrowserCommand';
import { LoggingEnableBrowserCommand } from './../commands/logging/enable/browser/LoggingEnableBrowserCommand';
import { LoggingStatusBrowserCommand } from './../commands/logging/status/browser/LoggingStatusBrowserCommand';
import { LogsConfigBrowserCommand } from './../commands/logs/config/browser/LogsConfigBrowserCommand';
import { LogsListBrowserCommand } from './../commands/logs/list/browser/LogsListBrowserCommand';
import { LogsReadBrowserCommand } from './../commands/logs/read/browser/LogsReadBrowserCommand';
import { LogsSearchBrowserCommand } from './../commands/logs/search/browser/LogsSearchBrowserCommand';
import { LogsStatsBrowserCommand } from './../commands/logs/stats/browser/LogsStatsBrowserCommand';
import { MediaPrewarmBrowserCommand } from './../commands/media/prewarm/browser/MediaPrewarmBrowserCommand';
import { MediaProcessBrowserCommand } from './../commands/media/process/browser/MediaProcessBrowserCommand';
import { MediaResizeBrowserCommand } from './../commands/media/resize/browser/MediaResizeBrowserCommand';
import { MigrationCutoverBrowserCommand } from './../commands/migration/cutover/browser/MigrationCutoverBrowserCommand';
import { MigrationPauseBrowserCommand } from './../commands/migration/pause/browser/MigrationPauseBrowserCommand';
import { MigrationResumeBrowserCommand } from './../commands/migration/resume/browser/MigrationResumeBrowserCommand';
import { MigrationRollbackBrowserCommand } from './../commands/migration/rollback/browser/MigrationRollbackBrowserCommand';
import { MigrationStartBrowserCommand } from './../commands/migration/start/browser/MigrationStartBrowserCommand';
import { MigrationStatusBrowserCommand } from './../commands/migration/status/browser/MigrationStatusBrowserCommand';
import { MigrationVerifyBrowserCommand } from './../commands/migration/verify/browser/MigrationVerifyBrowserCommand';
import { ModelDownloadBrowserCommand } from './../commands/model/download/browser/ModelDownloadBrowserCommand';
import { ModelForgeStatusBrowserCommand } from './../commands/model/forge-status/browser/ModelForgeStatusBrowserCommand';
import { ModelForgeBrowserCommand } from './../commands/model/forge/browser/ModelForgeBrowserCommand';
import { ModelIntrospectBrowserCommand } from './../commands/model/introspect/browser/ModelIntrospectBrowserCommand';
import { ModelListPublishedBrowserCommand } from './../commands/model/list-published/browser/ModelListPublishedBrowserCommand';
import { ModelPublishBrowserCommand } from './../commands/model/publish/browser/ModelPublishBrowserCommand';
import { ModelSearchBrowserCommand } from './../commands/model/search/browser/ModelSearchBrowserCommand';
import { PersonaAllocateBrowserCommand } from './../commands/persona/allocate/browser/PersonaAllocateBrowserCommand';
import { PersonaGenomeBrowserCommand } from './../commands/persona/genome/browser/PersonaGenomeBrowserCommand';
import { GenomeCaptureFeedbackBrowserCommand } from './../commands/persona/learning/capture-feedback/browser/GenomeCaptureFeedbackBrowserCommand';
import { GenomeCaptureInteractionBrowserCommand } from './../commands/persona/learning/capture-interaction/browser/GenomeCaptureInteractionBrowserCommand';
import { GenomeMultiAgentLearnBrowserCommand } from './../commands/persona/learning/multi-agent-learn/browser/GenomeMultiAgentLearnBrowserCommand';
import { PersonaLearningPatternCaptureBrowserCommand } from './../commands/persona/learning/pattern/capture/browser/PersonaLearningPatternCaptureBrowserCommand';
import { PersonaLearningPatternEndorseBrowserCommand } from './../commands/persona/learning/pattern/endorse/browser/PersonaLearningPatternEndorseBrowserCommand';
import { PersonaLearningPatternQueryBrowserCommand } from './../commands/persona/learning/pattern/query/browser/PersonaLearningPatternQueryBrowserCommand';
import { PingBrowserCommand } from './../commands/ping/browser/PingBrowserCommand';
import { PlasticityAnalyzeBrowserCommand } from './../commands/plasticity/analyze/browser/PlasticityAnalyzeBrowserCommand';
import { PlasticityCompactBrowserCommand } from './../commands/plasticity/compact/browser/PlasticityCompactBrowserCommand';
import { PlasticityCompressBrowserCommand } from './../commands/plasticity/compress/browser/PlasticityCompressBrowserCommand';
import { PlasticityPipelineBrowserCommand } from './../commands/plasticity/pipeline/browser/PlasticityPipelineBrowserCommand';
import { PlasticityTopologyBrowserCommand } from './../commands/plasticity/topology/browser/PlasticityTopologyBrowserCommand';
import { PositronCursorBrowserCommand } from './../commands/positron/cursor/browser/PositronCursorBrowserCommand';
import { ProcessRegistryBrowserCommand } from './../commands/process-registry/browser/ProcessRegistryBrowserCommand';
import { RuntimeMetricsBrowserCommand } from './../commands/runtime/metrics/browser/RuntimeMetricsBrowserCommand';
import { SentinelApproveBrowserCommand } from './../commands/sentinel/approve/browser/SentinelApproveBrowserCommand';
import { SentinelCodingAgentBrowserCommand } from './../commands/sentinel/coding-agent/browser/SentinelCodingAgentBrowserCommand';
import { SentinelEscalateBrowserCommand } from './../commands/sentinel/escalate/browser/SentinelEscalateBrowserCommand';
import { SentinelExtendBudgetBrowserCommand } from './../commands/sentinel/extend-budget/browser/SentinelExtendBudgetBrowserCommand';
import { SentinelResumeBrowserCommand } from './../commands/sentinel/resume/browser/SentinelResumeBrowserCommand';
import { SentinelRunBrowserCommand } from './../commands/sentinel/run/browser/SentinelRunBrowserCommand';
import { SentinelStatusBrowserCommand } from './../commands/sentinel/status/browser/SentinelStatusBrowserCommand';
import { SentinelWebResearchBrowserCommand } from './../commands/sentinel/web-research/browser/SentinelWebResearchBrowserCommand';
import { SessionCreateBrowserCommand } from './../commands/session/create/browser/SessionCreateBrowserCommand';
import { SessionDestroyBrowserCommand } from './../commands/session/destroy/browser/SessionDestroyBrowserCommand';
import { SessionGetIdBrowserCommand } from './../commands/session/get-id/browser/SessionGetIdBrowserCommand';
import { SessionGetUserBrowserCommand } from './../commands/session/get-user/browser/SessionGetUserBrowserCommand';
import { SkillActivateBrowserCommand } from './../commands/skill/activate/browser/SkillActivateBrowserCommand';
import { SkillGenerateBrowserCommand } from './../commands/skill/generate/browser/SkillGenerateBrowserCommand';
import { SkillListBrowserCommand } from './../commands/skill/list/browser/SkillListBrowserCommand';
import { SkillProposeBrowserCommand } from './../commands/skill/propose/browser/SkillProposeBrowserCommand';
import { SkillValidateBrowserCommand } from './../commands/skill/validate/browser/SkillValidateBrowserCommand';
import { StateContentCloseBrowserCommand } from './../commands/state/content/close/browser/StateContentCloseBrowserCommand';
import { StateContentSwitchBrowserCommand } from './../commands/state/content/switch/browser/StateContentSwitchBrowserCommand';
import { StateCreateBrowserCommand } from './../commands/state/create/browser/StateCreateBrowserCommand';
import { StateGetBrowserCommand } from './../commands/state/get/browser/StateGetBrowserCommand';
import { StateUpdateBrowserCommand } from './../commands/state/update/browser/StateUpdateBrowserCommand';
import { DaemonsBrowserCommand } from './../commands/system/daemons/browser/DaemonsBrowserCommand';
import { SystemDockerTierStatsBrowserCommand } from './../commands/system/docker-tier-stats/browser/SystemDockerTierStatsBrowserCommand';
import { SystemMetricsBrowserCommand } from './../commands/system/metrics/browser/SystemMetricsBrowserCommand';
import { SystemResourcesBrowserCommand } from './../commands/system/resources/browser/SystemResourcesBrowserCommand';
import { ThemeGetBrowserCommand } from './../commands/theme/get/browser/ThemeGetBrowserCommand';
import { ThemeListBrowserCommand } from './../commands/theme/list/browser/ThemeListBrowserCommand';
import { ThemeSetBrowserCommand } from './../commands/theme/set/browser/ThemeSetBrowserCommand';
import { TrainingImportBrowserCommand } from './../commands/training/import/browser/TrainingImportBrowserCommand';
import { UserCreateBrowserCommand } from './../commands/user/create/browser/UserCreateBrowserCommand';
import { UserGetMeBrowserCommand } from './../commands/user/get-me/browser/UserGetMeBrowserCommand';
import { UserListBrowserCommand } from './../commands/user/list/browser/UserListBrowserCommand';
import { DocsListBrowserCommand } from './../commands/utilities/docs/list/browser/DocsListBrowserCommand';
import { DocsReadBrowserCommand } from './../commands/utilities/docs/read/browser/DocsReadBrowserCommand';
import { DocsSearchBrowserCommand } from './../commands/utilities/docs/search/browser/DocsSearchBrowserCommand';
import { HelloBrowserCommand } from './../commands/utilities/hello/browser/HelloBrowserCommand';
import { VoiceSnapshotParticipantBrowserCommand } from './../commands/voice/snapshot-participant/browser/VoiceSnapshotParticipantBrowserCommand';
import { VoiceSnapshotRoomBrowserCommand } from './../commands/voice/snapshot-room/browser/VoiceSnapshotRoomBrowserCommand';
import { VoiceStartBrowserCommand } from './../commands/voice/start/browser/VoiceStartBrowserCommand';
import { VoiceStopBrowserCommand } from './../commands/voice/stop/browser/VoiceStopBrowserCommand';
import { VoiceSynthesizeBrowserCommand } from './../commands/voice/synthesize/browser/VoiceSynthesizeBrowserCommand';
import { VoiceTranscribeBrowserCommand } from './../commands/voice/transcribe/browser/VoiceTranscribeBrowserCommand';
import { GitCommitBrowserCommand } from './../commands/workspace/git/commit/browser/GitCommitBrowserCommand';
import { GitPushBrowserCommand } from './../commands/workspace/git/push/browser/GitPushBrowserCommand';
import { GitStatusBrowserCommand } from './../commands/workspace/git/status/browser/GitStatusBrowserCommand';
import { GitWorkspaceCleanBrowserCommand } from './../commands/workspace/git/workspace/clean/browser/GitWorkspaceCleanBrowserCommand';
import { GitWorkspaceInitBrowserCommand } from './../commands/workspace/git/workspace/init/browser/GitWorkspaceInitBrowserCommand';
import { ImageGenerateRealisticBrowserCommand } from './../commands/image/generate-realistic/browser/ImageGenerateRealisticBrowserCommand';
import { WorkspaceListBrowserCommand } from './../commands/workspace/list/browser/WorkspaceListBrowserCommand';
import { RecipeLoadBrowserCommand } from './../commands/workspace/recipe/load/browser/RecipeLoadBrowserCommand';
import { TaskCompleteBrowserCommand } from './../commands/workspace/task/complete/browser/TaskCompleteBrowserCommand';
import { TaskCreateBrowserCommand } from './../commands/workspace/task/create/browser/TaskCreateBrowserCommand';
import { TaskListBrowserCommand } from './../commands/workspace/task/list/browser/TaskListBrowserCommand';
import { TreeBrowserCommand } from './../commands/workspace/tree/browser/TreeBrowserCommand';

// Browser adapters Imports
import { UDPMulticastTransportBrowser } from './../system/transports/udp-multicast-transport/browser/UDPMulticastTransportBrowser';
import { WebSocketTransportClientBrowser } from './../system/transports/websocket-transport/browser/WebSocketTransportClientBrowser';

// Browser widgets Imports
import { ChatWidget } from './../widgets/chat/chat-widget/ChatWidget';
import { RoomListWidget } from './../widgets/chat/room-list/RoomListWidget';
import { UserListWidget } from './../widgets/chat/user-list/UserListWidget';
import { ContentTabsWidget } from './../widgets/content-tabs/ContentTabsWidget';
import { ContinuumEmoterWidget } from './../widgets/continuum-emoter/ContinuumEmoterWidget';
import { ContinuumMetricsWidget } from './../widgets/continuum-metrics/ContinuumMetricsWidget';
import { ContinuumWidget } from './../widgets/continuum/ContinuumWidget';
import { DiagnosticsWidget } from './../widgets/diagnostics/DiagnosticsWidget';
import { DrawingCanvasWidget } from './../widgets/drawing-canvas/DrawingCanvasWidget';
import { FactoryStatsWidget } from './../widgets/factory/FactoryStatsWidget';
import { FactoryWidget } from './../widgets/factory/FactoryWidget';
import { GenomeProfileWidget } from './../widgets/genome-profile/GenomeProfileWidget';
import { GridOverviewWidget } from './../widgets/grid/GridOverviewWidget';
import { HeaderControlsWidget } from './../widgets/header-controls/HeaderControlsWidget';
import { HelpWidget } from './../widgets/help/HelpWidget';
import { InferenceSampleWidget } from './../widgets/inference-sample/InferenceSampleWidget';
import { LiveWidget } from './../widgets/live/LiveWidget';
import { LogViewerWidget } from './../widgets/log-viewer/LogViewerWidget';
import { LogsNavWidget } from './../widgets/logs-nav/LogsNavWidget';
import { MainWidget } from './../widgets/main/MainWidget';
import { MetricsDetailWidget } from './../widgets/metrics-detail/MetricsDetailWidget';
import { WelcomeModalWidget } from './../widgets/onboarding/WelcomeModalWidget';
import { PersonaBrainWidget } from './../widgets/persona-brain/PersonaBrainWidget';
import { PositronCursorWidget } from './../widgets/positron-cursor/PositronCursorWidget';
import { RightPanelWidget } from './../widgets/right-panel/RightPanelWidget';
import { SettingsNavWidget } from './../widgets/settings-nav/SettingsNavWidget';
import { SettingsAssistantWidget } from './../widgets/settings/SettingsAssistantWidget';
import { SettingsWidget } from './../widgets/settings/SettingsWidget';
import { EmptyStateWidget } from './../widgets/shared/EmptyStateWidget';
import { ModalWidget } from './../widgets/shared/ModalWidget';
import { PanelLayoutWidget } from './../widgets/shared/PanelLayoutWidget';
import { UniverseWidget } from './../widgets/shared/UniverseWidget';
import { SidebarWidget } from './../widgets/sidebar/SidebarWidget';
import { TerminalWidget } from './../widgets/terminal/TerminalWidget';
import { TrainingDashboardWidget } from './../widgets/training-dashboard/TrainingDashboardWidget';
import { UserProfileWidget } from './../widgets/user-profile/UserProfileWidget';
import { WebViewWidget } from './../widgets/web-view/WebViewWidget';

// Types
import type { DaemonEntry } from './../daemons/command-daemon/shared/DaemonBase';
import type { CommandEntry } from './../daemons/command-daemon/shared/CommandBase';
import type { AdapterEntry } from './../system/transports/shared/TransportBase';
import type { WidgetEntry } from './../widgets/shared/WidgetBase';

/**
 * Browser Environment Registry
 */
export const BROWSER_DAEMONS: DaemonEntry[] = [
{
    name: 'ArchiveDaemon',
    className: 'ArchiveDaemonBrowser',
    daemonClass: ArchiveDaemonBrowser
  },
{
    name: 'ArtifactsDaemon',
    className: 'ArtifactsDaemonBrowser',
    daemonClass: ArtifactsDaemonBrowser
  },
{
    name: 'CommandDaemon',
    className: 'CommandDaemonBrowser',
    daemonClass: CommandDaemonBrowser
  },
{
    name: 'ConsoleDaemon',
    className: 'ConsoleDaemonBrowser',
    daemonClass: ConsoleDaemonBrowser
  },
{
    name: 'DataDaemon',
    className: 'DataDaemonBrowser',
    daemonClass: DataDaemonBrowser
  },
{
    name: 'EventsDaemon',
    className: 'EventsDaemonBrowser',
    daemonClass: EventsDaemonBrowser
  },
{
    name: 'HealthDaemon',
    className: 'HealthDaemonBrowser',
    daemonClass: HealthDaemonBrowser
  },
{
    name: 'LoggerDaemon',
    className: 'LoggerDaemonBrowser',
    daemonClass: LoggerDaemonBrowser
  },
{
    name: 'SessionDaemon',
    className: 'SessionDaemonBrowser',
    daemonClass: SessionDaemonBrowser
  },
{
    name: 'UserDaemon',
    className: 'UserDaemonBrowser',
    daemonClass: UserDaemonBrowser
  },
{
    name: 'WidgetDaemon',
    className: 'WidgetDaemonBrowser',
    daemonClass: WidgetDaemonBrowser
  }
];

export const BROWSER_COMMANDS: CommandEntry[] = [
{
    name: 'adapter/adopt',
    className: 'AdapterAdoptBrowserCommand',
    commandClass: AdapterAdoptBrowserCommand
  },
{
    name: 'adapter/publish',
    className: 'AdapterPublishBrowserCommand',
    commandClass: AdapterPublishBrowserCommand
  },
{
    name: 'adapter/search',
    className: 'AdapterSearchBrowserCommand',
    commandClass: AdapterSearchBrowserCommand
  },
{
    name: 'adapter/try',
    className: 'AdapterTryBrowserCommand',
    commandClass: AdapterTryBrowserCommand
  },
{
    name: 'agent/list',
    className: 'AgentListBrowserCommand',
    commandClass: AgentListBrowserCommand
  },
{
    name: 'agent/start',
    className: 'AgentStartBrowserCommand',
    commandClass: AgentStartBrowserCommand
  },
{
    name: 'agent/status',
    className: 'AgentStatusBrowserCommand',
    commandClass: AgentStatusBrowserCommand
  },
{
    name: 'agent/stop',
    className: 'AgentStopBrowserCommand',
    commandClass: AgentStopBrowserCommand
  },
{
    name: 'ai/agent',
    className: 'AiAgentBrowserCommand',
    commandClass: AiAgentBrowserCommand
  },
{
    name: 'ai/bag-of-words',
    className: 'BagOfWordsBrowserCommand',
    commandClass: BagOfWordsBrowserCommand
  },
{
    name: 'ai/context/search',
    className: 'AiContextSearchBrowserCommand',
    commandClass: AiContextSearchBrowserCommand
  },
{
    name: 'ai/context/slice',
    className: 'AiContextSliceBrowserCommand',
    commandClass: AiContextSliceBrowserCommand
  },
{
    name: 'ai/cost',
    className: 'AICostBrowserCommand',
    commandClass: AICostBrowserCommand
  },
{
    name: 'ai/detect-semantic-loop',
    className: 'AiDetectSemanticLoopBrowserCommand',
    commandClass: AiDetectSemanticLoopBrowserCommand
  },
{
    name: 'ai/generate',
    className: 'AIGenerateBrowserCommand',
    commandClass: AIGenerateBrowserCommand
  },
{
    name: 'ai/genome/stats',
    className: 'GenomeStatsBrowserCommand',
    commandClass: GenomeStatsBrowserCommand
  },
{
    name: 'ai/key/diff',
    className: 'AiKeyDiffBrowserCommand',
    commandClass: AiKeyDiffBrowserCommand
  },
{
    name: 'ai/key/remove',
    className: 'AiKeyRemoveBrowserCommand',
    commandClass: AiKeyRemoveBrowserCommand
  },
{
    name: 'ai/key/save',
    className: 'AiKeySaveBrowserCommand',
    commandClass: AiKeySaveBrowserCommand
  },
{
    name: 'ai/key/status',
    className: 'AiKeyStatusBrowserCommand',
    commandClass: AiKeyStatusBrowserCommand
  },
{
    name: 'ai/key/test',
    className: 'AiKeyTestBrowserCommand',
    commandClass: AiKeyTestBrowserCommand
  },
{
    name: 'ai/local-inference/start',
    className: 'AiLocalInferenceStartBrowserCommand',
    commandClass: AiLocalInferenceStartBrowserCommand
  },
{
    name: 'ai/local-inference/status',
    className: 'AiLocalInferenceStatusBrowserCommand',
    commandClass: AiLocalInferenceStatusBrowserCommand
  },
{
    name: 'ai/model/find',
    className: 'ModelFindBrowserCommand',
    commandClass: ModelFindBrowserCommand
  },
{
    name: 'ai/model/list',
    className: 'ModelListBrowserCommand',
    commandClass: ModelListBrowserCommand
  },
{
    name: 'ai/providers/status',
    className: 'AIProvidersStatusBrowserCommand',
    commandClass: AIProvidersStatusBrowserCommand
  },
{
    name: 'ai/rag/index-codebase',
    className: 'CodebaseIndexBrowserCommand',
    commandClass: CodebaseIndexBrowserCommand
  },
{
    name: 'ai/report',
    className: 'AIReportBrowserCommand',
    commandClass: AIReportBrowserCommand
  },
{
    name: 'ai/should-respond-fast',
    className: 'ShouldRespondFastBrowserCommand',
    commandClass: ShouldRespondFastBrowserCommand
  },
{
    name: 'ai/should-respond',
    className: 'AIShouldRespondBrowserCommand',
    commandClass: AIShouldRespondBrowserCommand
  },
{
    name: 'ai/sleep',
    className: 'AiSleepBrowserCommand',
    commandClass: AiSleepBrowserCommand
  },
{
    name: 'ai/status',
    className: 'AIStatusBrowserCommand',
    commandClass: AIStatusBrowserCommand
  },
{
    name: 'ai/thoughtstream',
    className: 'ThoughtStreamBrowserCommand',
    commandClass: ThoughtStreamBrowserCommand
  },
{
    name: 'ai/validate-response',
    className: 'AIValidateResponseBrowserCommand',
    commandClass: AIValidateResponseBrowserCommand
  },
{
    name: 'airc/bridge',
    className: 'AircBridgeBrowserCommand',
    commandClass: AircBridgeBrowserCommand
  },
{
    name: 'airc/send',
    className: 'AircSendBrowserCommand',
    commandClass: AircSendBrowserCommand
  },
{
    name: 'avatar/snapshot',
    className: 'AvatarSnapshotBrowserCommand',
    commandClass: AvatarSnapshotBrowserCommand
  },
{
    name: 'canvas/stroke/add',
    className: 'CanvasStrokeAddBrowserCommand',
    commandClass: CanvasStrokeAddBrowserCommand
  },
{
    name: 'canvas/stroke/list',
    className: 'CanvasStrokeListBrowserCommand',
    commandClass: CanvasStrokeListBrowserCommand
  },
{
    name: 'canvas/vision',
    className: 'CanvasVisionBrowserCommand',
    commandClass: CanvasVisionBrowserCommand
  },
{
    name: 'claude/context',
    className: 'ClaudeContextBrowserCommand',
    commandClass: ClaudeContextBrowserCommand
  },
{
    name: 'claude/resume',
    className: 'ClaudeResumeBrowserCommand',
    commandClass: ClaudeResumeBrowserCommand
  },
{
    name: 'claude/snapshot',
    className: 'ClaudeSnapshotBrowserCommand',
    commandClass: ClaudeSnapshotBrowserCommand
  },
{
    name: 'code/diff',
    className: 'CodeDiffBrowserCommand',
    commandClass: CodeDiffBrowserCommand
  },
{
    name: 'code/edit',
    className: 'CodeEditBrowserCommand',
    commandClass: CodeEditBrowserCommand
  },
{
    name: 'code/git',
    className: 'CodeGitBrowserCommand',
    commandClass: CodeGitBrowserCommand
  },
{
    name: 'code/history',
    className: 'CodeHistoryBrowserCommand',
    commandClass: CodeHistoryBrowserCommand
  },
{
    name: 'code/read',
    className: 'CodeReadBrowserCommand',
    commandClass: CodeReadBrowserCommand
  },
{
    name: 'code/search',
    className: 'CodeSearchBrowserCommand',
    commandClass: CodeSearchBrowserCommand
  },
{
    name: 'code/shell/execute',
    className: 'CodeShellExecuteBrowserCommand',
    commandClass: CodeShellExecuteBrowserCommand
  },
{
    name: 'code/shell/kill',
    className: 'CodeShellKillBrowserCommand',
    commandClass: CodeShellKillBrowserCommand
  },
{
    name: 'code/shell/sentinel',
    className: 'CodeShellSentinelBrowserCommand',
    commandClass: CodeShellSentinelBrowserCommand
  },
{
    name: 'code/shell/status',
    className: 'CodeShellStatusBrowserCommand',
    commandClass: CodeShellStatusBrowserCommand
  },
{
    name: 'code/shell/watch',
    className: 'CodeShellWatchBrowserCommand',
    commandClass: CodeShellWatchBrowserCommand
  },
{
    name: 'code/tree',
    className: 'CodeTreeBrowserCommand',
    commandClass: CodeTreeBrowserCommand
  },
{
    name: 'code/undo',
    className: 'CodeUndoBrowserCommand',
    commandClass: CodeUndoBrowserCommand
  },
{
    name: 'code/verify',
    className: 'CodeVerifyBrowserCommand',
    commandClass: CodeVerifyBrowserCommand
  },
{
    name: 'code/write',
    className: 'CodeWriteBrowserCommand',
    commandClass: CodeWriteBrowserCommand
  },
{
    name: 'cognition/admit-inbox-message',
    className: 'CognitionAdmitInboxMessageBrowserCommand',
    commandClass: CognitionAdmitInboxMessageBrowserCommand
  },
{
    name: 'cognition/recall-engrams',
    className: 'CognitionRecallEngramsBrowserCommand',
    commandClass: CognitionRecallEngramsBrowserCommand
  },
{
    name: 'cognition/vision-describe',
    className: 'CognitionVisionDescribeBrowserCommand',
    commandClass: CognitionVisionDescribeBrowserCommand
  },
{
    name: 'collaboration/activity/user-present',
    className: 'ActivityUserPresentCommand',
    commandClass: ActivityUserPresentCommand
  },
{
    name: 'collaboration/chat/analyze',
    className: 'ChatAnalyzeBrowserCommand',
    commandClass: ChatAnalyzeBrowserCommand
  },
{
    name: 'collaboration/chat/export',
    className: 'ChatExportBrowserCommand',
    commandClass: ChatExportBrowserCommand
  },
{
    name: 'collaboration/chat/poll',
    className: 'ChatPollBrowserCommand',
    commandClass: ChatPollBrowserCommand
  },
{
    name: 'collaboration/chat/send',
    className: 'ChatSendBrowserCommand',
    commandClass: ChatSendBrowserCommand
  },
{
    name: 'collaboration/content/open',
    className: 'ContentOpenBrowserCommand',
    commandClass: ContentOpenBrowserCommand
  },
{
    name: 'collaboration/decision/create',
    className: 'DecisionCreateBrowserCommand',
    commandClass: DecisionCreateBrowserCommand
  },
{
    name: 'collaboration/decision/finalize',
    className: 'DecisionFinalizeBrowserCommand',
    commandClass: DecisionFinalizeBrowserCommand
  },
{
    name: 'collaboration/decision/list',
    className: 'DecisionListBrowserCommand',
    commandClass: DecisionListBrowserCommand
  },
{
    name: 'collaboration/decision/propose',
    className: 'DecisionProposeBrowserCommand',
    commandClass: DecisionProposeBrowserCommand
  },
{
    name: 'collaboration/decision/rank',
    className: 'DecisionRankBrowserCommand',
    commandClass: DecisionRankBrowserCommand
  },
{
    name: 'collaboration/decision/view',
    className: 'DecisionViewBrowserCommand',
    commandClass: DecisionViewBrowserCommand
  },
{
    name: 'collaboration/decision/vote',
    className: 'DecisionVoteBrowserCommand',
    commandClass: DecisionVoteBrowserCommand
  },
{
    name: 'collaboration/dm',
    className: 'DmBrowserCommand',
    commandClass: DmBrowserCommand
  },
{
    name: 'collaboration/live/join',
    className: 'LiveJoinBrowserCommand',
    commandClass: LiveJoinBrowserCommand
  },
{
    name: 'collaboration/live/leave',
    className: 'LiveLeaveBrowserCommand',
    commandClass: LiveLeaveBrowserCommand
  },
{
    name: 'collaboration/live/start',
    className: 'CollaborationLiveStartBrowserCommand',
    commandClass: CollaborationLiveStartBrowserCommand
  },
{
    name: 'collaboration/live/transcription',
    className: 'CollaborationLiveTranscriptionBrowserCommand',
    commandClass: CollaborationLiveTranscriptionBrowserCommand
  },
{
    name: 'collaboration/wall/list',
    className: 'WallListBrowserCommand',
    commandClass: WallListBrowserCommand
  },
{
    name: 'collaboration/wall/read',
    className: 'WallReadBrowserCommand',
    commandClass: WallReadBrowserCommand
  },
{
    name: 'collaboration/wall/write',
    className: 'WallWriteBrowserCommand',
    commandClass: WallWriteBrowserCommand
  },
{
    name: 'continuum/emotion',
    className: 'EmotionBrowserCommand',
    commandClass: EmotionBrowserCommand
  },
{
    name: 'continuum/set',
    className: 'ContinuumSetBrowserCommand',
    commandClass: ContinuumSetBrowserCommand
  },
{
    name: 'data/backfill-vectors',
    className: 'BackfillVectorsBrowserCommand',
    commandClass: BackfillVectorsBrowserCommand
  },
{
    name: 'data/clear',
    className: 'DataClearBrowserCommand',
    commandClass: DataClearBrowserCommand
  },
{
    name: 'data/close',
    className: 'DataCloseBrowserCommand',
    commandClass: DataCloseBrowserCommand
  },
{
    name: 'data/create',
    className: 'DataCreateBrowserCommand',
    commandClass: DataCreateBrowserCommand
  },
{
    name: 'data/delete',
    className: 'DataDeleteBrowserCommand',
    commandClass: DataDeleteBrowserCommand
  },
{
    name: 'data/generate-embedding',
    className: 'GenerateEmbeddingBrowserCommand',
    commandClass: GenerateEmbeddingBrowserCommand
  },
{
    name: 'data/list-handles',
    className: 'DataListHandlesBrowserCommand',
    commandClass: DataListHandlesBrowserCommand
  },
{
    name: 'data/list',
    className: 'DataListBrowserCommand',
    commandClass: DataListBrowserCommand
  },
{
    name: 'data/open',
    className: 'DataOpenBrowserCommand',
    commandClass: DataOpenBrowserCommand
  },
{
    name: 'data/query-close',
    className: 'QueryCloseBrowserCommand',
    commandClass: QueryCloseBrowserCommand
  },
{
    name: 'data/query-next',
    className: 'QueryNextBrowserCommand',
    commandClass: QueryNextBrowserCommand
  },
{
    name: 'data/query-open',
    className: 'QueryOpenBrowserCommand',
    commandClass: QueryOpenBrowserCommand
  },
{
    name: 'data/read',
    className: 'DataReadBrowserCommand',
    commandClass: DataReadBrowserCommand
  },
{
    name: 'data/schema',
    className: 'DataSchemaBrowserCommand',
    commandClass: DataSchemaBrowserCommand
  },
{
    name: 'data/truncate',
    className: 'DataTruncateBrowserCommand',
    commandClass: DataTruncateBrowserCommand
  },
{
    name: 'data/update',
    className: 'DataUpdateBrowserCommand',
    commandClass: DataUpdateBrowserCommand
  },
{
    name: 'data/vector-search',
    className: 'VectorSearchBrowserCommand',
    commandClass: VectorSearchBrowserCommand
  },
{
    name: 'development/build',
    className: 'DevelopmentBuildBrowserCommand',
    commandClass: DevelopmentBuildBrowserCommand
  },
{
    name: 'development/code-smell',
    className: 'DevelopmentCodeSmellBrowserCommand',
    commandClass: DevelopmentCodeSmellBrowserCommand
  },
{
    name: 'development/compile-typescript',
    className: 'CompileTypescriptBrowserCommand',
    commandClass: CompileTypescriptBrowserCommand
  },
{
    name: 'development/debug/artifacts-check',
    className: 'ArtifactsCheckBrowserCommand',
    commandClass: ArtifactsCheckBrowserCommand
  },
{
    name: 'development/debug/chat-send',
    className: 'ChatSendDebugBrowserCommand',
    commandClass: ChatSendDebugBrowserCommand
  },
{
    name: 'development/debug/crud-sync',
    className: 'CrudSyncBrowserCommand',
    commandClass: CrudSyncBrowserCommand
  },
{
    name: 'development/debug/error',
    className: 'DebugErrorBrowserCommand',
    commandClass: DebugErrorBrowserCommand
  },
{
    name: 'development/debug/html-inspector',
    className: 'HtmlInspectorBrowserCommand',
    commandClass: HtmlInspectorBrowserCommand
  },
{
    name: 'development/debug/scroll-test',
    className: 'ScrollTestBrowserCommand',
    commandClass: ScrollTestBrowserCommand
  },
{
    name: 'development/debug/widget-css',
    className: 'WidgetCSSBrowserCommand',
    commandClass: WidgetCSSBrowserCommand
  },
{
    name: 'development/debug/widget-events',
    className: 'WidgetEventsDebugBrowserCommand',
    commandClass: WidgetEventsDebugBrowserCommand
  },
{
    name: 'development/debug/widget-interact',
    className: 'WidgetInteractBrowserCommand',
    commandClass: WidgetInteractBrowserCommand
  },
{
    name: 'development/debug/widget-state',
    className: 'WidgetStateBrowserCommand',
    commandClass: WidgetStateBrowserCommand
  },
{
    name: 'development/exec',
    className: 'ExecBrowserCommand',
    commandClass: ExecBrowserCommand
  },
{
    name: 'development/generate/audit',
    className: 'DevelopmentGenerateAuditBrowserCommand',
    commandClass: DevelopmentGenerateAuditBrowserCommand
  },
{
    name: 'development/generate',
    className: 'GenerateBrowserCommand',
    commandClass: GenerateBrowserCommand
  },
{
    name: 'development/generate/help',
    className: 'DevelopmentGenerateHelpBrowserCommand',
    commandClass: DevelopmentGenerateHelpBrowserCommand
  },
{
    name: 'development/generate/reverse',
    className: 'DevelopmentGenerateReverseBrowserCommand',
    commandClass: DevelopmentGenerateReverseBrowserCommand
  },
{
    name: 'development/schema/generate',
    className: 'SchemaGenerateBrowserCommand',
    commandClass: SchemaGenerateBrowserCommand
  },
{
    name: 'development/shell/execute',
    className: 'ShellExecuteBrowserCommand',
    commandClass: ShellExecuteBrowserCommand
  },
{
    name: 'development/verify-web',
    className: 'DevelopmentVerifyWebBrowserCommand',
    commandClass: DevelopmentVerifyWebBrowserCommand
  },
{
    name: 'file/append',
    className: 'FileAppendBrowserCommand',
    commandClass: FileAppendBrowserCommand
  },
{
    name: 'file/load',
    className: 'FileLoadBrowserCommand',
    commandClass: FileLoadBrowserCommand
  },
{
    name: 'file/mime-type',
    className: 'FileMimeTypeBrowserCommand',
    commandClass: FileMimeTypeBrowserCommand
  },
{
    name: 'file/save',
    className: 'FileSaveBrowserCommand',
    commandClass: FileSaveBrowserCommand
  },
{
    name: 'genome/academy-competition',
    className: 'GenomeAcademyCompetitionBrowserCommand',
    commandClass: GenomeAcademyCompetitionBrowserCommand
  },
{
    name: 'genome/academy-session-detail',
    className: 'GenomeAcademySessionDetailBrowserCommand',
    commandClass: GenomeAcademySessionDetailBrowserCommand
  },
{
    name: 'genome/academy-session-list',
    className: 'GenomeAcademySessionListBrowserCommand',
    commandClass: GenomeAcademySessionListBrowserCommand
  },
{
    name: 'genome/academy-session-restart',
    className: 'GenomeAcademySessionRestartBrowserCommand',
    commandClass: GenomeAcademySessionRestartBrowserCommand
  },
{
    name: 'genome/academy-session',
    className: 'GenomeAcademySessionBrowserCommand',
    commandClass: GenomeAcademySessionBrowserCommand
  },
{
    name: 'genome/adapter-backfill-metrics',
    className: 'GenomeAdapterBackfillMetricsBrowserCommand',
    commandClass: GenomeAdapterBackfillMetricsBrowserCommand
  },
{
    name: 'genome/adapter-update-metrics',
    className: 'GenomeAdapterUpdateMetricsBrowserCommand',
    commandClass: GenomeAdapterUpdateMetricsBrowserCommand
  },
{
    name: 'genome/batch-micro-tune',
    className: 'GenomeBatchMicroTuneBrowserCommand',
    commandClass: GenomeBatchMicroTuneBrowserCommand
  },
{
    name: 'genome/benchmark',
    className: 'GenomeBenchmarkBrowserCommand',
    commandClass: GenomeBenchmarkBrowserCommand
  },
{
    name: 'genome/convert',
    className: 'GenomeConvertBrowserCommand',
    commandClass: GenomeConvertBrowserCommand
  },
{
    name: 'genome/dataset-import',
    className: 'GenomeDatasetImportBrowserCommand',
    commandClass: GenomeDatasetImportBrowserCommand
  },
{
    name: 'genome/dataset-prepare',
    className: 'GenomeDatasetPrepareBrowserCommand',
    commandClass: GenomeDatasetPrepareBrowserCommand
  },
{
    name: 'genome/dataset-synthesize',
    className: 'GenomeDatasetSynthesizeBrowserCommand',
    commandClass: GenomeDatasetSynthesizeBrowserCommand
  },
{
    name: 'genome/demo-run',
    className: 'GenomeDemoRunBrowserCommand',
    commandClass: GenomeDemoRunBrowserCommand
  },
{
    name: 'genome/job-create',
    className: 'GenomeJobCreateBrowserCommand',
    commandClass: GenomeJobCreateBrowserCommand
  },
{
    name: 'genome/job-status',
    className: 'GenomeJobStatusBrowserCommand',
    commandClass: GenomeJobStatusBrowserCommand
  },
{
    name: 'genome/layers',
    className: 'GenomeLayersBrowserCommand',
    commandClass: GenomeLayersBrowserCommand
  },
{
    name: 'genome/train',
    className: 'GenomeTrainBrowserCommand',
    commandClass: GenomeTrainBrowserCommand
  },
{
    name: 'genome/train/list-jobs',
    className: 'GenomeTrainListJobsBrowserCommand',
    commandClass: GenomeTrainListJobsBrowserCommand
  },
{
    name: 'genome/train/resume',
    className: 'GenomeTrainResumeBrowserCommand',
    commandClass: GenomeTrainResumeBrowserCommand
  },
{
    name: 'genome/training-export',
    className: 'GenomeTrainingExportBrowserCommand',
    commandClass: GenomeTrainingExportBrowserCommand
  },
{
    name: 'genome/training-overview',
    className: 'GenomeTrainingOverviewBrowserCommand',
    commandClass: GenomeTrainingOverviewBrowserCommand
  },
{
    name: 'genome/training-pipeline',
    className: 'GenomeTrainingPipelineBrowserCommand',
    commandClass: GenomeTrainingPipelineBrowserCommand
  },
{
    name: 'gpu/stats',
    className: 'GpuStatsBrowserCommand',
    commandClass: GpuStatsBrowserCommand
  },
{
    name: 'grid/audit',
    className: 'GridAuditBrowserCommand',
    commandClass: GridAuditBrowserCommand
  },
{
    name: 'grid/deploy',
    className: 'GridDeployBrowserCommand',
    commandClass: GridDeployBrowserCommand
  },
{
    name: 'grid/discover',
    className: 'GridDiscoverBrowserCommand',
    commandClass: GridDiscoverBrowserCommand
  },
{
    name: 'grid/job-control',
    className: 'GridJobControlBrowserCommand',
    commandClass: GridJobControlBrowserCommand
  },
{
    name: 'grid/job-queue',
    className: 'GridJobQueueBrowserCommand',
    commandClass: GridJobQueueBrowserCommand
  },
{
    name: 'grid/job-submit',
    className: 'GridJobSubmitBrowserCommand',
    commandClass: GridJobSubmitBrowserCommand
  },
{
    name: 'grid/node-status',
    className: 'GridNodeStatusBrowserCommand',
    commandClass: GridNodeStatusBrowserCommand
  },
{
    name: 'grid/nodes',
    className: 'GridNodesBrowserCommand',
    commandClass: GridNodesBrowserCommand
  },
{
    name: 'grid/pair',
    className: 'GridPairBrowserCommand',
    commandClass: GridPairBrowserCommand
  },
{
    name: 'grid/ping',
    className: 'GridPingBrowserCommand',
    commandClass: GridPingBrowserCommand
  },
{
    name: 'grid/route',
    className: 'GridRouteBrowserCommand',
    commandClass: GridRouteBrowserCommand
  },
{
    name: 'grid/send',
    className: 'GridSendBrowserCommand',
    commandClass: GridSendBrowserCommand
  },
{
    name: 'grid/setup-check',
    className: 'GridSetupCheckBrowserCommand',
    commandClass: GridSetupCheckBrowserCommand
  },
{
    name: 'grid/status',
    className: 'GridStatusBrowserCommand',
    commandClass: GridStatusBrowserCommand
  },
{
    name: 'grid/trust',
    className: 'GridTrustBrowserCommand',
    commandClass: GridTrustBrowserCommand
  },
{
    name: 'help',
    className: 'HelpBrowserCommand',
    commandClass: HelpBrowserCommand
  },
{
    name: 'indicator',
    className: 'IndicatorBrowserCommand',
    commandClass: IndicatorBrowserCommand
  },
{
    name: 'inference/capacity',
    className: 'InferenceCapacityBrowserCommand',
    commandClass: InferenceCapacityBrowserCommand
  },
{
    name: 'inference/generate',
    className: 'InferenceGenerateBrowserCommand',
    commandClass: InferenceGenerateBrowserCommand
  },
{
    name: 'interface/browser/capabilities',
    className: 'InterfaceBrowserCapabilitiesBrowserCommand',
    commandClass: InterfaceBrowserCapabilitiesBrowserCommand
  },
{
    name: 'interface/click',
    className: 'ClickBrowserCommand',
    commandClass: ClickBrowserCommand
  },
{
    name: 'interface/get-text',
    className: 'GetTextBrowserCommand',
    commandClass: GetTextBrowserCommand
  },
{
    name: 'interface/interact',
    className: 'InterfaceInteractBrowserCommand',
    commandClass: InterfaceInteractBrowserCommand
  },
{
    name: 'interface/launch/url',
    className: 'InterfaceLaunchUrlBrowserCommand',
    commandClass: InterfaceLaunchUrlBrowserCommand
  },
{
    name: 'interface/navigate',
    className: 'NavigateBrowserCommand',
    commandClass: NavigateBrowserCommand
  },
{
    name: 'interface/page/fill',
    className: 'InterfacePageFillBrowserCommand',
    commandClass: InterfacePageFillBrowserCommand
  },
{
    name: 'interface/page/forms',
    className: 'InterfacePageFormsBrowserCommand',
    commandClass: InterfacePageFormsBrowserCommand
  },
{
    name: 'interface/page/submit',
    className: 'InterfacePageSubmitBrowserCommand',
    commandClass: InterfacePageSubmitBrowserCommand
  },
{
    name: 'interface/proxy-navigate',
    className: 'ProxyNavigateBrowserCommand',
    commandClass: ProxyNavigateBrowserCommand
  },
{
    name: 'interface/screenshot',
    className: 'ScreenshotBrowserCommand',
    commandClass: ScreenshotBrowserCommand
  },
{
    name: 'interface/scroll',
    className: 'ScrollBrowserCommand',
    commandClass: ScrollBrowserCommand
  },
{
    name: 'interface/type',
    className: 'TypeBrowserCommand',
    commandClass: TypeBrowserCommand
  },
{
    name: 'interface/wait-for-element',
    className: 'WaitForElementBrowserCommand',
    commandClass: WaitForElementBrowserCommand
  },
{
    name: 'interface/web/fetch',
    className: 'WebFetchBrowserCommand',
    commandClass: WebFetchBrowserCommand
  },
{
    name: 'interface/webmcp/call',
    className: 'InterfaceWebmcpCallBrowserCommand',
    commandClass: InterfaceWebmcpCallBrowserCommand
  },
{
    name: 'interface/webmcp/discover',
    className: 'InterfaceWebmcpDiscoverBrowserCommand',
    commandClass: InterfaceWebmcpDiscoverBrowserCommand
  },
{
    name: 'list',
    className: 'ListBrowserCommand',
    commandClass: ListBrowserCommand
  },
{
    name: 'logging/disable',
    className: 'LoggingDisableBrowserCommand',
    commandClass: LoggingDisableBrowserCommand
  },
{
    name: 'logging/enable',
    className: 'LoggingEnableBrowserCommand',
    commandClass: LoggingEnableBrowserCommand
  },
{
    name: 'logging/status',
    className: 'LoggingStatusBrowserCommand',
    commandClass: LoggingStatusBrowserCommand
  },
{
    name: 'logs/config',
    className: 'LogsConfigBrowserCommand',
    commandClass: LogsConfigBrowserCommand
  },
{
    name: 'logs/list',
    className: 'LogsListBrowserCommand',
    commandClass: LogsListBrowserCommand
  },
{
    name: 'logs/read',
    className: 'LogsReadBrowserCommand',
    commandClass: LogsReadBrowserCommand
  },
{
    name: 'logs/search',
    className: 'LogsSearchBrowserCommand',
    commandClass: LogsSearchBrowserCommand
  },
{
    name: 'logs/stats',
    className: 'LogsStatsBrowserCommand',
    commandClass: LogsStatsBrowserCommand
  },
{
    name: 'media/prewarm',
    className: 'MediaPrewarmBrowserCommand',
    commandClass: MediaPrewarmBrowserCommand
  },
{
    name: 'media/process',
    className: 'MediaProcessBrowserCommand',
    commandClass: MediaProcessBrowserCommand
  },
{
    name: 'media/resize',
    className: 'MediaResizeBrowserCommand',
    commandClass: MediaResizeBrowserCommand
  },
{
    name: 'migration/cutover',
    className: 'MigrationCutoverBrowserCommand',
    commandClass: MigrationCutoverBrowserCommand
  },
{
    name: 'migration/pause',
    className: 'MigrationPauseBrowserCommand',
    commandClass: MigrationPauseBrowserCommand
  },
{
    name: 'migration/resume',
    className: 'MigrationResumeBrowserCommand',
    commandClass: MigrationResumeBrowserCommand
  },
{
    name: 'migration/rollback',
    className: 'MigrationRollbackBrowserCommand',
    commandClass: MigrationRollbackBrowserCommand
  },
{
    name: 'migration/start',
    className: 'MigrationStartBrowserCommand',
    commandClass: MigrationStartBrowserCommand
  },
{
    name: 'migration/status',
    className: 'MigrationStatusBrowserCommand',
    commandClass: MigrationStatusBrowserCommand
  },
{
    name: 'migration/verify',
    className: 'MigrationVerifyBrowserCommand',
    commandClass: MigrationVerifyBrowserCommand
  },
{
    name: 'model/download',
    className: 'ModelDownloadBrowserCommand',
    commandClass: ModelDownloadBrowserCommand
  },
{
    name: 'model/forge-status',
    className: 'ModelForgeStatusBrowserCommand',
    commandClass: ModelForgeStatusBrowserCommand
  },
{
    name: 'model/forge',
    className: 'ModelForgeBrowserCommand',
    commandClass: ModelForgeBrowserCommand
  },
{
    name: 'model/introspect',
    className: 'ModelIntrospectBrowserCommand',
    commandClass: ModelIntrospectBrowserCommand
  },
{
    name: 'model/list-published',
    className: 'ModelListPublishedBrowserCommand',
    commandClass: ModelListPublishedBrowserCommand
  },
{
    name: 'model/publish',
    className: 'ModelPublishBrowserCommand',
    commandClass: ModelPublishBrowserCommand
  },
{
    name: 'model/search',
    className: 'ModelSearchBrowserCommand',
    commandClass: ModelSearchBrowserCommand
  },
{
    name: 'persona/allocate',
    className: 'PersonaAllocateBrowserCommand',
    commandClass: PersonaAllocateBrowserCommand
  },
{
    name: 'persona/genome',
    className: 'PersonaGenomeBrowserCommand',
    commandClass: PersonaGenomeBrowserCommand
  },
{
    name: 'persona/learning/capture-feedback',
    className: 'GenomeCaptureFeedbackBrowserCommand',
    commandClass: GenomeCaptureFeedbackBrowserCommand
  },
{
    name: 'persona/learning/capture-interaction',
    className: 'GenomeCaptureInteractionBrowserCommand',
    commandClass: GenomeCaptureInteractionBrowserCommand
  },
{
    name: 'persona/learning/multi-agent-learn',
    className: 'GenomeMultiAgentLearnBrowserCommand',
    commandClass: GenomeMultiAgentLearnBrowserCommand
  },
{
    name: 'persona/learning/pattern/capture',
    className: 'PersonaLearningPatternCaptureBrowserCommand',
    commandClass: PersonaLearningPatternCaptureBrowserCommand
  },
{
    name: 'persona/learning/pattern/endorse',
    className: 'PersonaLearningPatternEndorseBrowserCommand',
    commandClass: PersonaLearningPatternEndorseBrowserCommand
  },
{
    name: 'persona/learning/pattern/query',
    className: 'PersonaLearningPatternQueryBrowserCommand',
    commandClass: PersonaLearningPatternQueryBrowserCommand
  },
{
    name: 'ping',
    className: 'PingBrowserCommand',
    commandClass: PingBrowserCommand
  },
{
    name: 'plasticity/analyze',
    className: 'PlasticityAnalyzeBrowserCommand',
    commandClass: PlasticityAnalyzeBrowserCommand
  },
{
    name: 'plasticity/compact',
    className: 'PlasticityCompactBrowserCommand',
    commandClass: PlasticityCompactBrowserCommand
  },
{
    name: 'plasticity/compress',
    className: 'PlasticityCompressBrowserCommand',
    commandClass: PlasticityCompressBrowserCommand
  },
{
    name: 'plasticity/pipeline',
    className: 'PlasticityPipelineBrowserCommand',
    commandClass: PlasticityPipelineBrowserCommand
  },
{
    name: 'plasticity/topology',
    className: 'PlasticityTopologyBrowserCommand',
    commandClass: PlasticityTopologyBrowserCommand
  },
{
    name: 'positron/cursor',
    className: 'PositronCursorBrowserCommand',
    commandClass: PositronCursorBrowserCommand
  },
{
    name: 'process-registry',
    className: 'ProcessRegistryBrowserCommand',
    commandClass: ProcessRegistryBrowserCommand
  },
{
    name: 'runtime/metrics',
    className: 'RuntimeMetricsBrowserCommand',
    commandClass: RuntimeMetricsBrowserCommand
  },
{
    name: 'sentinel/approve',
    className: 'SentinelApproveBrowserCommand',
    commandClass: SentinelApproveBrowserCommand
  },
{
    name: 'sentinel/coding-agent',
    className: 'SentinelCodingAgentBrowserCommand',
    commandClass: SentinelCodingAgentBrowserCommand
  },
{
    name: 'sentinel/escalate',
    className: 'SentinelEscalateBrowserCommand',
    commandClass: SentinelEscalateBrowserCommand
  },
{
    name: 'sentinel/extend-budget',
    className: 'SentinelExtendBudgetBrowserCommand',
    commandClass: SentinelExtendBudgetBrowserCommand
  },
{
    name: 'sentinel/resume',
    className: 'SentinelResumeBrowserCommand',
    commandClass: SentinelResumeBrowserCommand
  },
{
    name: 'sentinel/run',
    className: 'SentinelRunBrowserCommand',
    commandClass: SentinelRunBrowserCommand
  },
{
    name: 'sentinel/status',
    className: 'SentinelStatusBrowserCommand',
    commandClass: SentinelStatusBrowserCommand
  },
{
    name: 'sentinel/web-research',
    className: 'SentinelWebResearchBrowserCommand',
    commandClass: SentinelWebResearchBrowserCommand
  },
{
    name: 'session/create',
    className: 'SessionCreateBrowserCommand',
    commandClass: SessionCreateBrowserCommand
  },
{
    name: 'session/destroy',
    className: 'SessionDestroyBrowserCommand',
    commandClass: SessionDestroyBrowserCommand
  },
{
    name: 'session/get-id',
    className: 'SessionGetIdBrowserCommand',
    commandClass: SessionGetIdBrowserCommand
  },
{
    name: 'session/get-user',
    className: 'SessionGetUserBrowserCommand',
    commandClass: SessionGetUserBrowserCommand
  },
{
    name: 'skill/activate',
    className: 'SkillActivateBrowserCommand',
    commandClass: SkillActivateBrowserCommand
  },
{
    name: 'skill/generate',
    className: 'SkillGenerateBrowserCommand',
    commandClass: SkillGenerateBrowserCommand
  },
{
    name: 'skill/list',
    className: 'SkillListBrowserCommand',
    commandClass: SkillListBrowserCommand
  },
{
    name: 'skill/propose',
    className: 'SkillProposeBrowserCommand',
    commandClass: SkillProposeBrowserCommand
  },
{
    name: 'skill/validate',
    className: 'SkillValidateBrowserCommand',
    commandClass: SkillValidateBrowserCommand
  },
{
    name: 'state/content/close',
    className: 'StateContentCloseBrowserCommand',
    commandClass: StateContentCloseBrowserCommand
  },
{
    name: 'state/content/switch',
    className: 'StateContentSwitchBrowserCommand',
    commandClass: StateContentSwitchBrowserCommand
  },
{
    name: 'state/create',
    className: 'StateCreateBrowserCommand',
    commandClass: StateCreateBrowserCommand
  },
{
    name: 'state/get',
    className: 'StateGetBrowserCommand',
    commandClass: StateGetBrowserCommand
  },
{
    name: 'state/update',
    className: 'StateUpdateBrowserCommand',
    commandClass: StateUpdateBrowserCommand
  },
{
    name: 'system/daemons',
    className: 'DaemonsBrowserCommand',
    commandClass: DaemonsBrowserCommand
  },
{
    name: 'system/docker-tier-stats',
    className: 'SystemDockerTierStatsBrowserCommand',
    commandClass: SystemDockerTierStatsBrowserCommand
  },
{
    name: 'system/metrics',
    className: 'SystemMetricsBrowserCommand',
    commandClass: SystemMetricsBrowserCommand
  },
{
    name: 'system/resources',
    className: 'SystemResourcesBrowserCommand',
    commandClass: SystemResourcesBrowserCommand
  },
{
    name: 'theme/get',
    className: 'ThemeGetBrowserCommand',
    commandClass: ThemeGetBrowserCommand
  },
{
    name: 'theme/list',
    className: 'ThemeListBrowserCommand',
    commandClass: ThemeListBrowserCommand
  },
{
    name: 'theme/set',
    className: 'ThemeSetBrowserCommand',
    commandClass: ThemeSetBrowserCommand
  },
{
    name: 'training/import',
    className: 'TrainingImportBrowserCommand',
    commandClass: TrainingImportBrowserCommand
  },
{
    name: 'user/create',
    className: 'UserCreateBrowserCommand',
    commandClass: UserCreateBrowserCommand
  },
{
    name: 'user/get-me',
    className: 'UserGetMeBrowserCommand',
    commandClass: UserGetMeBrowserCommand
  },
{
    name: 'user/list',
    className: 'UserListBrowserCommand',
    commandClass: UserListBrowserCommand
  },
{
    name: 'utilities/docs/list',
    className: 'DocsListBrowserCommand',
    commandClass: DocsListBrowserCommand
  },
{
    name: 'utilities/docs/read',
    className: 'DocsReadBrowserCommand',
    commandClass: DocsReadBrowserCommand
  },
{
    name: 'utilities/docs/search',
    className: 'DocsSearchBrowserCommand',
    commandClass: DocsSearchBrowserCommand
  },
{
    name: 'utilities/hello',
    className: 'HelloBrowserCommand',
    commandClass: HelloBrowserCommand
  },
{
    name: 'voice/snapshot-participant',
    className: 'VoiceSnapshotParticipantBrowserCommand',
    commandClass: VoiceSnapshotParticipantBrowserCommand
  },
{
    name: 'voice/snapshot-room',
    className: 'VoiceSnapshotRoomBrowserCommand',
    commandClass: VoiceSnapshotRoomBrowserCommand
  },
{
    name: 'voice/start',
    className: 'VoiceStartBrowserCommand',
    commandClass: VoiceStartBrowserCommand
  },
{
    name: 'voice/stop',
    className: 'VoiceStopBrowserCommand',
    commandClass: VoiceStopBrowserCommand
  },
{
    name: 'voice/synthesize',
    className: 'VoiceSynthesizeBrowserCommand',
    commandClass: VoiceSynthesizeBrowserCommand
  },
{
    name: 'voice/transcribe',
    className: 'VoiceTranscribeBrowserCommand',
    commandClass: VoiceTranscribeBrowserCommand
  },
{
    name: 'workspace/git/commit',
    className: 'GitCommitBrowserCommand',
    commandClass: GitCommitBrowserCommand
  },
{
    name: 'workspace/git/push',
    className: 'GitPushBrowserCommand',
    commandClass: GitPushBrowserCommand
  },
{
    name: 'workspace/git/status',
    className: 'GitStatusBrowserCommand',
    commandClass: GitStatusBrowserCommand
  },
{
    name: 'workspace/git/workspace/clean',
    className: 'GitWorkspaceCleanBrowserCommand',
    commandClass: GitWorkspaceCleanBrowserCommand
  },
{
    name: 'workspace/git/workspace/init',
    className: 'GitWorkspaceInitBrowserCommand',
    commandClass: GitWorkspaceInitBrowserCommand
  },
{
    name: 'image/generate-realistic',
    className: 'ImageGenerateRealisticBrowserCommand',
    commandClass: ImageGenerateRealisticBrowserCommand
  },
{
    name: 'workspace/list',
    className: 'WorkspaceListBrowserCommand',
    commandClass: WorkspaceListBrowserCommand
  },
{
    name: 'workspace/recipe/load',
    className: 'RecipeLoadBrowserCommand',
    commandClass: RecipeLoadBrowserCommand
  },
{
    name: 'workspace/task/complete',
    className: 'TaskCompleteBrowserCommand',
    commandClass: TaskCompleteBrowserCommand
  },
{
    name: 'workspace/task/create',
    className: 'TaskCreateBrowserCommand',
    commandClass: TaskCreateBrowserCommand
  },
{
    name: 'workspace/task/list',
    className: 'TaskListBrowserCommand',
    commandClass: TaskListBrowserCommand
  },
{
    name: 'workspace/tree',
    className: 'TreeBrowserCommand',
    commandClass: TreeBrowserCommand
  }
];

export const BROWSER_ADAPTERS: AdapterEntry[] = [
{
    name: 'u-d-p-multicast-transport-browser',
    className: 'UDPMulticastTransportBrowser',
    adapterClass: UDPMulticastTransportBrowser,
    protocol: 'websocket', // TODO: Extract from transport type
    supportedRoles: ['client', 'server'], // TODO: Extract from class metadata
    supportedEnvironments: ['{env}'] // Current environment
  },
{
    name: 'web-socket-transport-client-browser',
    className: 'WebSocketTransportClientBrowser',
    adapterClass: WebSocketTransportClientBrowser,
    protocol: 'websocket', // TODO: Extract from transport type
    supportedRoles: ['client', 'server'], // TODO: Extract from class metadata
    supportedEnvironments: ['{env}'] // Current environment
  }
];

export const BROWSER_WIDGETS: WidgetEntry[] = [
{
    name: 'Chat',
    className: 'ChatWidget',
    widgetClass: ChatWidget,
    tagName: 'Chat'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'RoomList',
    className: 'RoomListWidget',
    widgetClass: RoomListWidget,
    tagName: 'RoomList'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'UserList',
    className: 'UserListWidget',
    widgetClass: UserListWidget,
    tagName: 'UserList'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'ContentTabs',
    className: 'ContentTabsWidget',
    widgetClass: ContentTabsWidget,
    tagName: 'ContentTabs'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'ContinuumEmoter',
    className: 'ContinuumEmoterWidget',
    widgetClass: ContinuumEmoterWidget,
    tagName: 'ContinuumEmoter'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'ContinuumMetrics',
    className: 'ContinuumMetricsWidget',
    widgetClass: ContinuumMetricsWidget,
    tagName: 'ContinuumMetrics'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'Continuum',
    className: 'ContinuumWidget',
    widgetClass: ContinuumWidget,
    tagName: 'Continuum'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'Diagnostics',
    className: 'DiagnosticsWidget',
    widgetClass: DiagnosticsWidget,
    tagName: 'Diagnostics'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'DrawingCanvas',
    className: 'DrawingCanvasWidget',
    widgetClass: DrawingCanvasWidget,
    tagName: 'DrawingCanvas'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'FactoryStats',
    className: 'FactoryStatsWidget',
    widgetClass: FactoryStatsWidget,
    tagName: 'FactoryStats'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'Factory',
    className: 'FactoryWidget',
    widgetClass: FactoryWidget,
    tagName: 'Factory'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'GenomeProfile',
    className: 'GenomeProfileWidget',
    widgetClass: GenomeProfileWidget,
    tagName: 'GenomeProfile'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'GridOverview',
    className: 'GridOverviewWidget',
    widgetClass: GridOverviewWidget,
    tagName: 'GridOverview'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'HeaderControls',
    className: 'HeaderControlsWidget',
    widgetClass: HeaderControlsWidget,
    tagName: 'HeaderControls'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'Help',
    className: 'HelpWidget',
    widgetClass: HelpWidget,
    tagName: 'Help'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'InferenceSample',
    className: 'InferenceSampleWidget',
    widgetClass: InferenceSampleWidget,
    tagName: 'InferenceSample'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'Live',
    className: 'LiveWidget',
    widgetClass: LiveWidget,
    tagName: 'Live'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'LogViewer',
    className: 'LogViewerWidget',
    widgetClass: LogViewerWidget,
    tagName: 'LogViewer'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'LogsNav',
    className: 'LogsNavWidget',
    widgetClass: LogsNavWidget,
    tagName: 'LogsNav'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'Main',
    className: 'MainWidget',
    widgetClass: MainWidget,
    tagName: 'Main'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'MetricsDetail',
    className: 'MetricsDetailWidget',
    widgetClass: MetricsDetailWidget,
    tagName: 'MetricsDetail'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'WelcomeModal',
    className: 'WelcomeModalWidget',
    widgetClass: WelcomeModalWidget,
    tagName: 'WelcomeModal'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'PersonaBrain',
    className: 'PersonaBrainWidget',
    widgetClass: PersonaBrainWidget,
    tagName: 'PersonaBrain'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'PositronCursor',
    className: 'PositronCursorWidget',
    widgetClass: PositronCursorWidget,
    tagName: 'PositronCursor'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'RightPanel',
    className: 'RightPanelWidget',
    widgetClass: RightPanelWidget,
    tagName: 'RightPanel'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'SettingsNav',
    className: 'SettingsNavWidget',
    widgetClass: SettingsNavWidget,
    tagName: 'SettingsNav'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'SettingsAssistant',
    className: 'SettingsAssistantWidget',
    widgetClass: SettingsAssistantWidget,
    tagName: 'SettingsAssistant'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'Settings',
    className: 'SettingsWidget',
    widgetClass: SettingsWidget,
    tagName: 'Settings'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'EmptyState',
    className: 'EmptyStateWidget',
    widgetClass: EmptyStateWidget,
    tagName: 'EmptyState'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'Modal',
    className: 'ModalWidget',
    widgetClass: ModalWidget,
    tagName: 'Modal'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'PanelLayout',
    className: 'PanelLayoutWidget',
    widgetClass: PanelLayoutWidget,
    tagName: 'PanelLayout'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'Universe',
    className: 'UniverseWidget',
    widgetClass: UniverseWidget,
    tagName: 'Universe'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'Sidebar',
    className: 'SidebarWidget',
    widgetClass: SidebarWidget,
    tagName: 'Sidebar'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'Terminal',
    className: 'TerminalWidget',
    widgetClass: TerminalWidget,
    tagName: 'Terminal'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'TrainingDashboard',
    className: 'TrainingDashboardWidget',
    widgetClass: TrainingDashboardWidget,
    tagName: 'TrainingDashboard'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'UserProfile',
    className: 'UserProfileWidget',
    widgetClass: UserProfileWidget,
    tagName: 'UserProfile'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  },
{
    name: 'WebView',
    className: 'WebViewWidget',
    widgetClass: WebViewWidget,
    tagName: 'WebView'.replace(/([A-Z])/g, (match, p1, offset) => offset > 0 ? '-' + p1.toLowerCase() : p1.toLowerCase()) + '-widget'
  }
];
